import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1512,height:1000},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
try {
 await page.goto('http://127.0.0.1:5178');await page.waitForFunction(()=>!!window.evDebug);await page.waitForTimeout(400);
 assert.match(await page.locator('#vehicle-variant').innerText(),/V2 RWD Uzun Menzil/);assert.ok(await page.locator('#vehicle-variant').isVisible());
 const finish=()=>page.evaluate(()=>{let n=300;while(!['done','failed'].includes(evDebug.sim.status)&&n--)evDebug.advance();if(n<=0)throw Error('Loop guard');return {status:evDebug.sim.status,state:evDebug.sim.state,trace:evDebug.sim.trace};});
 const playbackPosition=await page.evaluate(()=>({play:document.querySelector('#play').getBoundingClientRect().bottom,model:document.querySelector('#viewport').getBoundingClientRect().top}));assert.ok(playbackPosition.play<=playbackPosition.model,'Playback controls above 3D viewport');
 const visibleDisplays=await page.evaluate(()=>['cluster-display','ivi-display','control-display'].every(id=>{const r=document.getElementById(id).getBoundingClientRect();return r.top>0&&r.bottom<innerHeight;}));assert.ok(visibleDisplays,'Both cockpit screens visible in first viewport');
 await page.screenshot({path:'tests/pro-desktop.png',fullPage:true});
 await page.locator('#exterior').click();await page.waitForTimeout(200);assert.equal(await page.evaluate(()=>evDebug.scene.stats().exterior),true);assert.equal(await page.locator('.part-label:visible').count(),0);await page.screenshot({path:'tests/t10f-exterior.png',fullPage:true});await page.locator('#exterior').click();await page.waitForTimeout(200);
 const dimensions=await page.evaluate(()=>evDebug.scene.stats().dimensions);assert.equal(dimensions.length,4.83);assert.ok(Math.abs(dimensions.wheelbase-2.89)<1e-9);
 await page.locator('#cockpit-reference').click();assert.ok(await page.locator('.cockpit-reference-image').isVisible());await page.locator('#close-dialog').click();await page.locator('#cockpit-expand').click();assert.ok(await page.locator('.togg-cockpit.expanded').isVisible());await page.screenshot({path:'tests/togg-cockpit-expanded.png',fullPage:true});await page.locator('#cockpit-expand').click();
 const pixelCounts=await page.evaluate(()=>{const r=evDebug.scene.renderer,g=r.getContext(),w=r.domElement.width,h=r.domElement.height,data=new Uint8Array(w*h*4);g.readPixels(0,0,w,h,g.RGBA,g.UNSIGNED_BYTE,data);const unique=new Set();let saturated=0;for(let i=0;i<data.length;i+=32){unique.add(`${data[i]},${data[i+1]},${data[i+2]}`);if(Math.max(data[i],data[i+1],data[i+2])-Math.min(data[i],data[i+1],data[i+2])>40)saturated++;}return {colors:unique.size,saturated};});assert.ok(pixelCounts.colors>300&&pixelCounts.saturated>100);
 const focusBefore=await page.evaluate(()=>evDebug.scene.camera.position.toArray());await page.locator('#next').click();await page.waitForTimeout(400);const focus=await page.evaluate(()=>({position:evDebug.scene.camera.position.toArray(),muted:Object.values(evDebug.scene.parts).filter(p=>p.material.opacity<.2).length,active:evDebug.scene.stats().active}));assert.ok(focus.active);assert.ok(focus.muted>30);assert.notDeepEqual(focus.position,focusBefore);await page.screenshot({path:'tests/togg-flow-focus.png',fullPage:true});await page.locator('#follow-flow').click();assert.equal(await page.evaluate(()=>evDebug.scene.stats().follow),false);await page.locator('#follow-flow').click();
 for(let i=0;i<24;i++){await page.locator(`[data-scenario="${i}"]`).click();const r=await finish();assert.equal(r.status,i===20?'failed':'done',`Scenario ${i}`);}
 await page.locator('[data-scenario="15"]').click();await page.locator('#cut-window').click();let result=await finish();assert.equal(result.state.window,0);assert.equal(result.status,'failed');assert.ok(await page.locator('#trace').innerText().then(t=>t.includes('TIMEOUT')));
 await page.locator('#repair').click();await page.locator('[data-screen="vehicle"]').click();await page.locator('[data-scenario="0"]').click();await page.locator('#window-open').click();result=await finish();assert.equal(result.state.windowReported,1);await page.locator('#window-close').click();result=await finish();assert.equal(result.state.windowReported,0);
 await page.locator('#window-slider').fill('60');result=await finish();assert.equal(result.state.windowReported,.6);
 await page.locator('[data-scenario="17"]').click();await page.locator('#temp-plus').click();await page.locator('#temp-plus').click();await page.locator('#climate-on').click();result=await finish();assert.equal(result.state.targetTemp,24);assert.equal(result.state.ac,true);await page.locator('#climate-on').click();result=await finish();assert.equal(result.state.ac,false);
 await page.locator('[data-screen="media"]').click();await page.locator('#pair-phone').click();await finish();await page.locator('#music-play').click();result=await finish();assert.equal(result.state.music,true);await page.screenshot({path:'tests/pro-media.png',fullPage:true});
 await page.locator('[data-screen="navigation"]').click();await page.locator('#route-start').click();await finish();await page.locator('[data-screen="energy"]').click();await page.locator('#ac-charge').click();result=await finish();assert.equal(result.state.charging,true);await page.locator('#charge-stop').click();result=await finish();assert.equal(result.state.plug,false);
 await page.locator('[data-scenario="0"]').click();await page.locator('#play').click();await page.waitForTimeout(1100);await page.locator('#play').click();const paused=await page.evaluate(()=>evDebug.sim.time);await page.waitForTimeout(1100);assert.equal(await page.evaluate(()=>evDebug.sim.time),paused);
 await page.locator('[data-panel="inspect"]').click();await page.locator('#component-select').selectOption('bcm');await page.locator('[data-cut="bcm:window:lin"]').click();assert.ok(await page.evaluate(()=>evDebug.sim.cuts.has('bcm:window:lin')));await page.locator('[data-cut="bcm:window:lin"]').click();await page.locator('#node-offline').check();assert.ok(await page.evaluate(()=>evDebug.sim.offline.has('bcm')));await page.locator('#node-offline').uncheck();
 await page.locator('#sources').click();assert.ok(await page.locator('#doc-content tbody tr').count()>=15);await page.locator('[data-doc="sources"]').click();assert.ok(await page.locator('.reference').count()>=15);await page.locator('[data-doc="assumptions"]').click();assert.ok(await page.locator('#doc-content tbody tr').count()>=9);await page.screenshot({path:'tests/pro-references.png',fullPage:true});await page.locator('#close-dialog').click();
 const downloadPromise=page.waitForEvent('download');await page.locator('#export').click();const report=await downloadPromise;await report.saveAs('tests/example-report.json');const reportData=JSON.parse(await (await import('node:fs/promises')).readFile('tests/example-report.json','utf8'));assert.equal(reportData.vehicleProfile.grossCapacityKWh,89.6);assert.equal(reportData.vehicleProfile.usableCapacityKWh,null);
 assert.equal(reportData.audit.homologationVerified,false);assert.equal(reportData.audit.oemFirmware,null);assert.equal(new Set(reportData.systemAudit.flatMap(s=>s.components)).size,47);
 await page.locator('#sources').click();await page.locator('[data-doc="audit"]').click();assert.equal(await page.locator('#doc-content tbody tr').count(),11);assert.match(await page.locator('#doc-content').innerText(),/V2 RWD Uzun Menzil/);await page.screenshot({path:'tests/pro-audit.png',fullPage:true});await page.locator('#close-dialog').click();
 const before=await page.evaluate(()=>evDebug.scene.camera.position.toArray());const box=await page.locator('#viewport canvas').boundingBox();await page.mouse.move(box.x+box.width*.25,box.y+box.height*.8);await page.mouse.down();await page.mouse.move(box.x+box.width*.25+90,box.y+box.height*.8+20,{steps:10});await page.mouse.up();await page.waitForTimeout(200);assert.notDeepEqual(await page.evaluate(()=>evDebug.scene.camera.position.toArray()),before);
 await page.locator('#home').click();await page.locator('#explode').fill('1');await page.locator('#explode').dispatchEvent('input');assert.equal(await page.evaluate(()=>evDebug.scene.stats().exploded),1);await page.screenshot({path:'tests/pro-exploded.png',fullPage:true});await page.locator('#explode').fill('0');await page.locator('#explode').dispatchEvent('input');
 await page.locator('[data-screen="vehicle"]').click();await page.locator('[data-scenario="1"]').click();await finish();const motionA=await page.locator('#viewport canvas').screenshot();await page.waitForTimeout(250);const motionB=await page.locator('#viewport canvas').screenshot();assert.ok(!motionA.equals(motionB));
 await page.setViewportSize({width:390,height:844});await page.locator('[data-scenario="0"]').click();await page.locator('#home').click();await page.waitForTimeout(300);await page.screenshot({path:'tests/pro-mobile.png',fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.ok(await page.evaluate(()=>['cluster-display','ivi-display','control-display'].every(id=>document.getElementById(id).getBoundingClientRect().bottom<innerHeight)));
 assert.ok(await page.locator('#vehicle-variant').isVisible());
 assert.equal(errors.length,0,errors.join('\n'));console.log(JSON.stringify({scenarios:24,pixelCounts,desktopAndMobile:true,cockpitInSameViewport:true,controls:true,faultInjection:true,sources:true,audit:true,downloads:true,animation:true,errors}));
} finally {await browser.close();}
