import './professional.css';
import './playback-toolbar.css';
import './togg-cockpit.css';
import {cockpitMarkup,paintMap} from './togg-cockpit.js';
import {createIcons,icons} from 'lucide';
import {components,wires,types,byId} from './architecture.js';
import {Simulation,scenarios} from './simulation.js';
import {references,requirements,assumptions,reviewDate} from './references.js';
import {audit,systemAudit} from './audit.js';
import {vehicleProfile,vehicleFacts} from './vehicle-profile.js';
import {createScene} from './scene-v2.js';
const icon=n=>`<i data-lucide="${n}"></i>`;
const $=s=>document.querySelector(s);
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
document.querySelector('#app').innerHTML=`<header><div class="brand"><span>${icon('circuit-board')}</span><strong>EV ATÖLYE</strong><b>02</b><span class="header-description">Araç sistem laboratuvarı</span></div><div class="header-actions"><span class="market">M1 · AB · BEV</span><button id="sources">${icon('book-open')}<span>Kaynaklar & kapsam</span></button><button id="export" title="Deney raporunu JSON indir">${icon('download')}</button></div></header>
<div class="scope-strip"><span class="dot"></span>T10F referansı · İç mimari temsili · Uygunluk doğrulanmadı<span class="review-date">Kaynak incelemesi: 05.09.2026</span></div>
<main><aside class="library"><div class="section-heading">DENEY KÜTÜPHANESİ <b>${scenarios.length}</b></div><label class="search">${icon('search')}<input id="search" placeholder="Senaryo ara" aria-label="Senaryo ara"></label><div id="scenario-list"></div><div class="library-footer">${components.filter(c=>!c.external&&!c.bus).length} araç bileşeni · ${wires.length} bağlantı</div></aside>
<section class="workbench"><div class="model-heading"><div><h1>${vehicleProfile.name}</h1><p class="vehicle-variant" id="vehicle-variant">${vehicleProfile.variant}</p></div><div class="segmented" id="layers"><button data-layer="network" class="active">Ağ</button><button data-layer="power">Güç</button><button data-layer="thermal">Termal</button><button data-layer="all">Tümü</button></div></div>
<section class="experiment experiment-toolbar"><div class="experiment-head"><div><div class="eyebrow" id="experiment-index"></div><h2 id="experiment-name"></h2></div><div class="play-controls"><select id="rate" aria-label="Görsel oynatma hızı"><option value="1">1×</option><option value="2">2×</option><option value=".5">0,5×</option></select><button id="restart" title="Başlangıç koşullarına dön">${icon('rotate-ccw')}</button><button id="play" class="primary">${icon('play')}Başlat</button><button id="next" title="Bir aktarım ilerle">${icon('step-forward')}</button></div></div><div class="progress"><i id="progress-fill"></i></div><div class="experiment-meta"><span id="step-caption">Beklemede</span><span id="clock">0 ms · sanal zaman</span></div></section>
<div id="viewport"><div class="scene-tools"><button id="home" title="Perspektif görünüm">${icon('rotate-3d')}</button><button id="top" title="Üst görünüm">${icon('scan')}</button><button id="body" title="Hayalet gövdeyi göster / gizle" class="active">${icon('car-front')}</button><button id="follow-flow" title="Akışı kamerayla takip et" class="active">${icon('focus')}</button><button id="exterior" title="Dış tasarım / iç mimari">${icon('paintbrush')}</button><button id="labels" title="Tüm etiketler">${icon('tags')}</button><button id="shot" title="3D görünümü indir">${icon('camera')}</button></div><div id="packet-status" class="packet-status">Ağ beklemede</div><div class="model-annotation">ÖN AKS ← <span>Yerleşim ve demet güzergahları: tasarım varsayımı</span></div></div>
<div class="legend-row"><div id="legend">${Object.entries(types).filter(([k])=>!['signal','pilot'].includes(k)).map(([k,t])=>`<button data-bus="${k}"><span style="background:${t.color}"></span>${t.label}</button>`).join('')}</div><label>Ayrıştır <input id="explode" type="range" min="0" max="1" step=".01" value="0" aria-label="Bileşenleri ayrıştır"></label></div>
${cockpitMarkup(icon)}
<div class="experiment-sources" id="scenario-refs"></div>
</section><aside class="right-panel"><div class="right-tabs"><button data-panel="trace" class="active">Mesaj akışı</button><button data-panel="inspect">Bileşen</button><button data-panel="faults">Arıza</button></div><section id="panel-trace"><div class="trace-head"><strong id="run-status">BEKLEMEDE</strong><span id="event-count">0 olay</span></div><div class="trace-columns"><span>ms</span><span>İşlem / mesaj</span></div><div id="trace"></div><div class="trace-foot">Sanal süreler · Model parametreleri</div><div class="section-heading state-heading">GERÇEK DURUM / HMI</div><div id="state-comparison"></div><div class="quick-fault"><button id="cut-window">${icon('scissors')}Cam LIN hattını kes</button><button id="repair">${icon('wrench')}Arızaları temizle</button></div></section>
<section id="panel-inspect" hidden><select id="component-select" aria-label="İncelenecek bileşen">${components.map(c=>`<option value="${c.id}">${c.tag} · ${c.name}</option>`).join('')}</select><div id="component-info"></div><label class="offline-toggle"><input id="node-offline" type="checkbox">Düğümü devre dışı bırak</label><div class="section-heading">FİZİKSEL / MANTIKSAL BAĞLANTILAR</div><div id="connections"></div></section>
<section id="panel-faults" hidden><h2>Deney girdileri</h2><p class="muted">Seçili deney başlangıcına uygulanır. Hat ve düğüm arızaları deneyler arasında korunur.</p><div id="inputs">${[['authorized','Yetkili komut',true],['keyAuthorized','Anahtar yetkisi',true],['brake','Fren pedalı',true],['park','Park durumu',true],['network','Hücresel erişim',true],['main12','Ana 12 V besleme',true],['backup','eCall yedek besleme',true],['isolation','İzolasyon kontrolü',true],['prechargeIntact','Ön şarj direnci sağlam',true],['obstruction','Camda engel',false],['updateAuthentic','OTA imzası geçerli (girdi)',true],['updateBootOK','OTA yeni slot sağlıklı',true]].map(([id,l,v])=>`<label><span>${l}</span><input data-input="${id}" type="checkbox" ${v?'checked':''}></label>`).join('')}</div><button id="apply-inputs" class="primary">Girdilerle yeniden kur</button><p class="muted">Kriptografik doğrulama sonucu bir girdidir; anahtar veya imza hesaplanmaz.</p><div id="fault-summary"></div></section></aside></main>
<dialog id="reference-dialog"><div class="dialog-head"><div><span class="eyebrow">AB / M1 / KAYNAK İNCELEMESİ ${reviewDate}</span><h2>Dayanaklar ve doğrulama kapsamı</h2></div><button id="close-dialog" title="Kapat">${icon('x')}</button></div><div class="dialog-tabs"><button data-doc="audit">Denetim kaydı</button><button data-doc="matrix" class="active">Gereksinim matrisi</button><button data-doc="sources">Kaynak kütüphanesi</button><button data-doc="assumptions">Model varsayımları</button></div><div id="doc-content"></div></dialog>`;
const sim=new Simulation();let scene,playing=false,rate=1,elapsed=0,selected='gw',screenTab='home',panel='trace',showBody=true,labelMode=false,tempTarget=22;
const symbols=()=>createIcons({icons});
scene=createScene($('#viewport'),id=>{selectComponent(id);showPanel('inspect');});
function refButton(id){return `<button class="ref-button" data-ref="${id}">${references[id].kind==='Mevzuat'?icon('scale'):icon('book-open')}${references[id].title}</button>`;}
function bindRefs(root=document){root.querySelectorAll('[data-ref]').forEach(b=>b.onclick=()=>openDocs('sources',b.dataset.ref));root.querySelectorAll('[data-focus]').forEach(b=>b.onclick=()=>{selectComponent(b.dataset.focus);showPanel('inspect');});}
function renderList(){const q=$('#search').value.toLocaleLowerCase('tr');$('#scenario-list').innerHTML=['Sürüş','Enerji','Konfor','Bağlantı','Güvenlik'].map(group=>{const found=scenarios.map((s,i)=>({...s,i})).filter(s=>s.group===group&&s.name.toLocaleLowerCase('tr').includes(q));return found.length?`<h3>${group}</h3>${found.map(s=>`<button data-scenario="${s.i}" class="scenario ${sim.scenarioIndex===s.i?'active':''}"><small>${String(s.i+1).padStart(2,'0')}</small>${icon(s.icon)}<span>${s.name}</span></button>`).join('')}`:'';}).join('')||'<p class="muted">Sonuç bulunamadı.</p>';document.querySelectorAll('[data-scenario]').forEach(b=>b.onclick=()=>choose(Number(b.dataset.scenario)));symbols();}
function choose(index,options){playing=false;sim.reset(index,options);elapsed=0;scene.setEvent(null);tempTarget=sim.state.targetTemp;syncInputs();renderList();update();}
function syncInputs(){document.querySelectorAll('[data-input]').forEach(e=>e.checked=!!sim.state[e.dataset.input]);}
function showPanel(id){panel=id;for(const p of ['trace','inspect','faults'])$('#panel-'+p).hidden=p!==id;document.querySelectorAll('[data-panel]').forEach(b=>b.classList.toggle('active',b.dataset.panel===id));}
function selectComponent(id){selected=id;scene.select(id);$('#component-select').value=id;const c=byId[id];$('#component-info').innerHTML=`<div class="component-tag" style="color:${types[c.type].color}">${c.tag} <span>${c.bus?'Bus kesimi':c.external?'Harici uç':'Araç bileşeni'}</span></div><h2>${c.name}</h2><p>${c.description}</p><dl><dt>Arayüz</dt><dd>${c.spec}</dd><dt>Konum</dt><dd>${c.pos.map(n=>n.toFixed(2)).join(' / ')} m</dd><dt>Yerleşim</dt><dd>Tasarım varsayımı</dd><dt>ASIL</dt><dd>HARA / tahsis yapılmadı</dd></dl><div class="source-stack">${c.refs.map(refButton).join('')}</div>`;$('#node-offline').checked=sim.offline.has(id);const connected=wires.filter(w=>w.from===id||w.to===id);$('#connections').innerHTML=connected.map(w=>{const other=w.from===id?w.to:w.from;return `<div class="connection"><button data-focus="${other}"><span style="background:${types[w.type].color}"></span><b>${byId[other].tag}</b><small>${w.label}</small></button><button data-cut="${w.id}" class="${sim.cuts.has(w.id)?'cut':''}" title="${sim.cuts.has(w.id)?'Hattı onar':'Hattı kes'}">${icon(sim.cuts.has(w.id)?'link':'scissors')}</button></div>`;}).join('');$('#connections').querySelectorAll('[data-cut]').forEach(b=>b.onclick=()=>{sim.cut(b.dataset.cut,!sim.cuts.has(b.dataset.cut));updateFaults();selectComponent(selected);update();});bindRefs($('#panel-inspect'));symbols();}
function updateFaults(){scene.setFaults(sim.cuts,sim.offline);$('#fault-summary').textContent=`${sim.cuts.size} kesik hat · ${sim.offline.size} kapalı düğüm`;$('#cut-window').classList.toggle('cut',sim.cuts.has('bcm:window:lin'));}
function renderTrace(){const root=$('#trace');root.innerHTML=sim.trace.slice(-100).map(e=>`<div class="trace-row ${e.status.toLowerCase()}" data-event="${e.seq}"><time>${e.time.toLocaleString('tr')}</time><div><div class="trace-title"><b class="event-status">${e.status}</b><span style="color:${types[e.bus]?.color||'#73828d'}">${e.bus?types[e.bus].label:'SİSTEM'}</span>${e.from?`<strong>${byId[e.from].tag} → ${byId[e.to].tag}</strong>`:''}</div><p>${escape(e.signal)}</p><small>${escape(e.detail)}</small></div></div>`).join('');root.scrollTop=root.scrollHeight;root.querySelectorAll('[data-event]').forEach(row=>row.onclick=()=>{playing=false;const event=sim.trace.find(e=>e.seq===Number(row.dataset.event));scene.setEvent(event.edge?event:null);$('#packet-status').textContent=event.from?`${byId[event.from].tag} → ${byId[event.to].tag} · ${event.signal}`:event.signal;renderPlay();});$('#event-count').textContent=sim.trace.length+' olay';}
function renderPlay(){$('#play').innerHTML=icon(playing?'pause':'play')+(playing?'Duraklat':sim.status==='done'||sim.status==='failed'?'Tekrar':'Başlat');$('#next').disabled=['done','failed'].includes(sim.status);$('#run-status').textContent={idle:'BEKLEMEDE',running:playing?'ÇALIŞIYOR':'DURAKLATILDI',done:'TAMAMLANDI',failed:sim.scenario.expected==='rejected'?'BEKLENEN RED':'DURDURULDU'}[sim.status];$('#run-status').className=sim.status;symbols();}
function update(){const s=sim.state;$('#experiment-index').textContent=`DENEY ${String(sim.scenarioIndex+1).padStart(2,'0')} / ${scenarios.length} · ${s.command?'IVI KOMUTU':sim.scenario.group.toLocaleUpperCase('tr')}`;$('#experiment-name').textContent=s.command?`Ekran komutu: ${s.command}`:sim.scenario.name;$('#progress-fill').style.width=`${sim.cursor/sim.queue.length*100}%`;$('#step-caption').textContent=sim.failure||`${sim.cursor} / ${sim.queue.length} işlem`;$('#clock').textContent=`${sim.time.toLocaleString('tr')} ms · sanal`;$('#scenario-refs').innerHTML=sim.scenario.refs.map(refButton).join('');bindRefs($('#scenario-refs'));renderPlay();renderTrace();renderDisplays();updateFaults();$('#state-comparison').innerHTML=[['Cam / HMI',`%${Math.round(s.window*100)} / %${Math.round(s.windowReported*100)}`],['DC-link / batarya',`${s.busV.toFixed(1)} / ${s.voltage} V`],['HV kontaktör',s.hv?'Kapalı (enerjili)':'Açık (ayrılmış)'],['Ana / yedek LV',`${s.main12?'Var':'Yok'} / ${s.backup?'Var':'Yok'}`],['Örnek OTA / slot',`${s.ota} / ${s.slot}`]].map(([a,b])=>`<div><span>${a}</span><strong>${b}</strong></div>`).join('');symbols();}
function advance(){const e=sim.next();scene.setEvent(sim.active);$('#packet-status').textContent=e?.from?`${byId[e.from].tag} → ${byId[e.to].tag} · ${e.signal}`:e?.label||'Deney tamamlandı';if(['done','failed'].includes(sim.status))playing=false;update();return e;}
function command(name,value){playing=false;sim.command(name,value);playing=true;elapsed=0;advance();showPanel('trace');}
function launch(id,preserve=true){choose(scenarios.findIndex(s=>s.id===id),{preserve});playing=true;advance();showPanel('trace');}
function renderDisplays(){const s=sim.state,d=s.display;$('#cluster-display').classList.toggle('off',!sim.powered('cluster'));$('#ivi-display').classList.toggle('off',!sim.powered('screen'));$('#control-display').classList.toggle('disabled',!sim.powered('screen'));$('#cluster-link').textContent=sim.powered('cluster')?(sim.circuit(['gw','cluster'],'eth')?'ETH / çevrimiçi':'ETH / bağlantı kesik'):'Besleme yok';$('#ivi-link').textContent=sim.powered('screen')?(sim.circuit(['gw','screen'],'eth')?'VHAL / çevrimiçi':'Gateway bağlantısı kesik'):'Besleme yok';$('#icm-speed').textContent=Math.round(Math.abs(d.speed));$('#icm-power').textContent=d.power.toFixed(1);$('#icm-soc').textContent=d.soc.toFixed(1)+'%';$('#icm-temp').textContent=d.temp.toFixed(1)+' °C';$('#battery-fill').style.width=d.soc+'%';$('#power-fill').style.width=Math.min(100,Math.abs(d.power)/vehicleProfile.maxPowerKW*100)+'%';$('#power-fill').classList.toggle('regen',d.power<0);$('#icm-voltage').textContent='DC-link '+Math.round(d.busV)+' V';$('#icm-ecall').textContent='eCall · '+s.ecall;$('#icm-warning').textContent=d.fault||d.mode;$('#icm-warning').classList.toggle('warning',!!d.fault);for(const [id,on] of [['ready',d.ready],['lights',s.lights],['brake',s.park],['fault',!!s.fault],['charge',s.plug]])$('#tell-'+id).classList.toggle('lit',on);document.querySelectorAll('[data-gear]').forEach(g=>g.classList.toggle('selected',g.dataset.gear===d.gear));$('#ivi-network').textContent=s.lte?'LTE bağlı':'LTE çevrimdışı';$('#ivi-phone').textContent=s.phone?'Telefon bağlı':'Telefon yok';$('#temp-target').textContent=tempTarget+'°';$('#cabin-value').textContent='Kabin '+s.reportedCabin.toFixed(1)+'°';$('#climate-on').classList.toggle('active',s.ac);$('#upper-soc').textContent=d.soc.toFixed(1)+'%';$('#upper-power').textContent=d.power.toFixed(1)+' kW';$('#upper-weather').textContent=s.cabin.toFixed(0)+' °C';$('#upper-status').textContent=s.mode;$('#upper-media').hidden=!s.music;$('#ivi-time').textContent=new Date().toLocaleTimeString('tr',{hour:'2-digit',minute:'2-digit'});renderScreen();}
function renderScreen(){const s=sim.state,root=$('#ivi-content');$('#control-title').textContent=({home:'Ana ekran',vehicle:'Araç kontrolleri',media:'Medya',navigation:'Navigasyon',energy:'Enerji'})[screenTab];document.querySelectorAll('[data-screen]').forEach(b=>b.classList.toggle('active',screenTab===b.dataset.screen));if(s.camera){root.innerHTML=`<div class="camera-view"><canvas id="camera-preview" width="600" height="220"></canvas><span>GERİ GÖRÜŞ · TEMSİLİ</span><button id="camera-dismiss" title="Kamera görünümünü kapat">${icon('x')}</button></div>`;const c=$('#camera-preview').getContext('2d');c.fillStyle='#2a3639';c.fillRect(0,0,600,220);c.fillStyle='#62706d';c.fillRect(0,0,600,58);c.strokeStyle='#adddbd';c.lineWidth=4;for(const x of [100,500]){c.beginPath();c.moveTo(x,220);c.lineTo(x<300?240:360,60);c.stroke();}for(const [y,color]of [[170,'#ed987d'],[115,'#ead583'],[75,'#adddbd']]){c.strokeStyle=color;c.beginPath();c.moveTo(100+(220-y)*.87,y);c.lineTo(500-(220-y)*.87,y);c.stroke();}$('#camera-dismiss').onclick=()=>{s.camera=false;renderScreen();};}
 else if(screenTab==='home'){root.innerHTML=`<div class="togg-app-grid">${[['media','music-2','Medya'],['navigation','navigation','Trumore Gez'],['vehicle','car-front','Araç'],['energy','zap','Enerji']].map(([id,i,l])=>`<button data-app="${id}"><span>${icon(i)}</span><small>${l}</small></button>`).join('')}</div>`;root.querySelectorAll('[data-app]').forEach(b=>b.onclick=()=>setScreen(b.dataset.app));}
 else if(screenTab==='vehicle'){root.innerHTML=`<div class="vehicle-controls"><div class="ivi-title"><h3>Araç</h3><span>${s.locked?'Kilitli':'Kilit açık'}</span></div><div class="window-control"><div><span>Sol ön cam</span><b>%${Math.round(s.windowReported*100)} açık</b></div><input id="window-slider" type="range" min="0" max="100" value="${Math.round(s.windowReported*100)}" aria-label="Sol ön cam açıklığı"><div class="window-actions"><button id="window-close" title="Camı kapat">${icon('chevron-up')}</button><button id="window-open" title="Camı aç">${icon('chevron-down')}</button><span id="window-feedback">${sim.failure?'Komut başarısız':s.window!==s.windowReported?'Geri bildirim bekleniyor':'Pozisyon alındı'}</span></div></div><div class="ivi-actions"><button id="door-lock" title="${s.locked?'Kilidi aç':'Kilitle'}">${icon(s.locked?'lock-keyhole':'lock-keyhole-open')}</button><button id="lamp-toggle" class="${s.lights?'active':''}" title="Farlar">${icon('lightbulb')}</button><button id="wiper-toggle" class="${s.wiper?'active':''}" title="Silecek">${icon('wind')}</button><button id="vehicle-start" class="start-control">${icon('power')}<span>${s.ready?'Kapat':'Çalıştır'}</span></button></div></div>`;$('#window-slider').onchange=e=>command('window',Number(e.target.value)/100);$('#window-open').onclick=()=>command('window',1);$('#window-close').onclick=()=>command('window',0);$('#door-lock').onclick=()=>command('lock',!s.locked);$('#lamp-toggle').onclick=()=>command('lights',!s.lights);$('#wiper-toggle').onclick=()=>command('wiper',!s.wiper);$('#vehicle-start').onclick=()=>launch(s.ready?'stop':'start');}
 else if(screenTab==='media'){root.innerHTML=`<div class="media-screen"><div class="album">${icon('audio-lines')}</div><div><span class="ivi-eyebrow">TELEFON MEDYASI</span><h3>Elektrik</h3><p>Örnek parça · Ambient</p><div class="media-controls"><button id="pair-phone">${icon('bluetooth')}Eşleştir</button><button id="music-play" title="${s.music?'Medyayı durdur':'Medyayı oynat'}">${icon(s.music?'pause':'play')}</button></div><small>${s.music?'A²B → AMP → hoparlör':'Ses akışı beklemede'}</small></div></div>`;$('#pair-phone').onclick=()=>launch('phone');$('#music-play').onclick=()=>{if(s.music){s.music=false;s.media='Medya duraklatıldı';sim.emit('INPUT',null,'MediaPause','IVI yerel medya oturumu durdu');update();}else command('media',true);};}
 else if(screenTab==='navigation'){root.innerHTML=`<div class="nav-screen"><canvas id="map-preview" width="500" height="210"></canvas><div><span>ÖRNEK ROTA</span><h3>Şarj istasyonu</h3><button id="route-start">${icon('navigation')}Rota başlat</button></div></div>`;const c=$('#map-preview').getContext('2d');c.fillStyle='#283b3b';c.fillRect(0,0,500,210);c.strokeStyle='#466060';c.lineWidth=7;for(let i=0;i<8;i++){c.beginPath();c.moveTo(i*75,0);c.lineTo(i*65+45,210);c.stroke();}for(let y=35;y<210;y+=55){c.beginPath();c.moveTo(0,y);c.lineTo(500,y-20);c.stroke();}c.strokeStyle='#6bd7b1';c.lineWidth=6;c.beginPath();c.moveTo(280,210);c.lineTo(245,120);c.lineTo(400,108);c.lineTo(377,37);c.stroke();$('#route-start').onclick=()=>launch('nav');}
 else {root.innerHTML=`<div class="energy-screen"><div><span>BATARYA</span><h3>${s.soc.toFixed(1)}<small>%</small></h3><p>${s.charging?'Şarj ediliyor':'Şarj bağlantısı bekleniyor'}</p></div><div><strong>${s.power.toFixed(1)} kW</strong><span>${s.temp.toFixed(1)} °C</span></div><div class="charge-actions"><button id="ac-charge">AC</button><button id="dc-charge">DC</button><button id="charge-stop" title="Şarjı sonlandır">${icon('unplug')}</button></div></div>`;$('#ac-charge').onclick=()=>launch('accharge');$('#dc-charge').onclick=()=>launch('dccharge');$('#charge-stop').onclick=()=>launch('unplug');}symbols();}
function openDocs(tab='matrix',ref){const dialog=$('#reference-dialog');if(!dialog.open)dialog.showModal();document.querySelectorAll('[data-doc]').forEach(b=>b.classList.toggle('active',b.dataset.doc===tab));const root=$('#doc-content');if(tab==='audit'){root.innerHTML=`<h3>${audit.vehicle}</h3><p class="document-intro">${audit.market} · Katalog: ${audit.brochure} · Denetim: ${audit.date}<br><strong>${audit.verdict}</strong><br>Gerçek Togg/Trumore yazılım sürümü: bilinmiyor. OTA 3.4.1 / 3.5.0 yalnız örnek sürümlerdir.</p><h3>Düzeltilen bulgular</h3><ul class="audit-findings">${audit.corrections.map(s=>`<li>${s}</li>`).join('')}</ul><h3>Sistem kapsamı · ${components.length} düğüm</h3><div class="table-scroll"><table><thead><tr><th>Sistem</th><th>Yazılımda olan</th><th>Olmayan / doğrulanmayan</th></tr></thead><tbody>${systemAudit.map(s=>`<tr><td><strong>${s.system}</strong><small>${s.components.map(id=>byId[id].tag).join(', ')}</small></td><td>${s.implemented}</td><td>${s.missing}</td></tr>`).join('')}</tbody></table></div>`;}else if(tab==='cockpit'){root.innerHTML=`<h3>Togg T10F · Görsel referans</h3><img class="cockpit-reference-image" src="${import.meta.env.BASE_URL}assets/t10f-cockpit-photo.jpg" alt="Togg T10F gerçek kokpit ve üç ekran düzeni"><p class="document-intro">Üst panoramik ekran ve alt kumanda düzeni bu fotoğrafla karşılaştırıldı. Yazılım sürümü fotoğrafta doğrulanamıyor. Görünen yerleşim yeniden çizildi; tüm menülerde piksel düzeyinde eşlik veya OEM yazılımı iddiası yoktur.</p><p><a href="https://www.tgrthaber.com/aktuel/togg-t10f-kampanya-finansman-destegi-sifir-faizli-kredi-destegiyle-satisa-cikti-3249130" target="_blank" rel="noopener">Fotoğrafın yayımlandığı sayfa · 15.09.2025</a> · <a href="https://www.togg.com.tr/t10f" target="_blank" rel="noopener">Togg resmî T10F sayfası</a></p>`;}else if(tab==='matrix')root.innerHTML=`<p class="document-intro">M1 binek BEV için başlangıç izlenebilirlik matrisi. “Davranış testi”, bu yazılımın koşulunu ifade eder; mevzuata uygunluk veya homologasyon sonucu değildir. Uygulanacak seri, üretim yolu ve başvuru tarihi ayrıca kesinleştirilmelidir.</p><div class="table-scroll"><table><thead><tr><th>ID / gereksinim</th><th>Dayanak</th><th>Model kapsamı</th><th>Eksik gerçek kanıt</th></tr></thead><tbody>${requirements.map(r=>`<tr><td><small>${r.id}</small><strong>${r.title}</strong></td><td>${refButton(r.ref)}<small>${r.section}</small></td><td><span class="coverage ${r.coverage==='Modellenmedi'?'absent':''}">${r.coverage}</span></td><td>${r.evidence}</td></tr>`).join('')}</tbody></table></div>`;
 else if(tab==='sources')root.innerHTML=`<p class="document-intro">Birincil mevzuat ve üretici/standart ekosistemi kaynakları. Özetler seçilen model davranışını gerekçelendirir; tüm düzenleme maddelerini uyguladığı iddia edilmez.</p>${Object.entries(references).map(([id,r])=>`<article class="reference" id="ref-${id}"><span>${r.kind}</span><h3><a href="${r.url}" target="_blank" rel="noopener noreferrer">${r.title}${icon('external-link')}</a></h3><small>${r.section}</small><p class="audit-source-status">${audit.sources[id].checkedOn} · ${audit.sources[id].result}</p><p>${r.summary}</p><div>${r.limit}</div></article>`).join('')}`;
 else root.innerHTML=`<p class="document-intro">Referans: Togg T10F V2 RWD Uzun Menzil, Türkiye kataloğu (15.06.2026). Üretici verileri ile aşağıdaki simülasyon tercihleri ayrıdır. İç mimari Togg tarafından doğrulanmamıştır. Tüm veriler deney raporuna eklenir.</p><div class="table-scroll"><table><thead><tr><th>Üretici verisi</th><th>Değer</th><th>Dayanak / sınır</th></tr></thead><tbody>${vehicleFacts.map(a=>`<tr>${a.map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}</tbody></table></div><p class="document-intro"><a href="${vehicleProfile.source}" target="_blank" rel="noopener">Resmî T10F kataloğu</a> · Simülasyon tercihleri</p><div class="table-scroll"><table><thead><tr><th>ID</th><th>Alan</th><th>Değer / tercih</th><th>Sınır</th></tr></thead><tbody>${assumptions.map(a=>`<tr>${a.map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;bindRefs(root);symbols();if(ref)setTimeout(()=>$('#ref-'+ref)?.scrollIntoView({block:'start'}),30);}
function setScreen(tab){screenTab=tab;sim.state.camera=false;renderScreen();symbols();}
$('#search').oninput=renderList;document.querySelectorAll('[data-panel]').forEach(b=>b.onclick=()=>showPanel(b.dataset.panel));document.querySelectorAll('[data-screen]').forEach(b=>b.onclick=()=>{setScreen(b.dataset.screen);});document.querySelectorAll('[data-layer]').forEach(b=>b.onclick=()=>{scene.setLayer(b.dataset.layer);document.querySelectorAll('[data-layer]').forEach(x=>x.classList.toggle('active',x===b));});document.querySelectorAll('[data-bus]').forEach(b=>b.onclick=()=>{scene.setLayer(b.dataset.bus);document.querySelectorAll('[data-bus]').forEach(x=>x.classList.toggle('active',x===b));});
$('#play').onclick=()=>{if(['done','failed'].includes(sim.status))choose(sim.scenarioIndex);playing=!playing;elapsed=0;if(playing&&sim.cursor===0)advance();renderPlay();};$('#next').onclick=()=>{playing=false;advance();};$('#restart').onclick=()=>choose(sim.scenarioIndex);$('#rate').onchange=e=>rate=Number(e.target.value);$('#home').onclick=()=>scene.home();$('#top').onclick=()=>scene.home(true);$('#body').onclick=()=>{showBody=!showBody;scene.setBody(showBody);$('#body').classList.toggle('active',showBody);};$('#follow-flow').onclick=()=>{const on=$('#follow-flow').classList.toggle('active');scene.setFollow(on);};$('#exterior').onclick=()=>{const on=$('#exterior').classList.toggle('active');scene.setExterior(on);};$('#labels').onclick=()=>{labelMode=!labelMode;scene.setLabels(true,labelMode);$('#labels').classList.toggle('active',labelMode);};$('#explode').oninput=e=>scene.setExplode(Number(e.target.value));$('#component-select').onchange=e=>selectComponent(e.target.value);$('#node-offline').onchange=e=>{sim.setOffline(selected,e.target.checked);update();};
$('#cut-window').onclick=()=>{const id='bcm:window:lin';sim.cut(id,!sim.cuts.has(id));update();};$('#repair').onclick=()=>{sim.cuts.clear();sim.offline.clear();sim.emit('REPAIR',null,'Arızalar temizlendi','Hat ve düğüm arızaları sıfırlandı');update();selectComponent(selected);};$('#apply-inputs').onclick=()=>{const inputs=Object.fromEntries([...document.querySelectorAll('[data-input]')].map(e=>[e.dataset.input,e.checked]));choose(sim.scenarioIndex,{inputs});};
$('#temp-minus').onclick=()=>{tempTarget=Math.max(16,tempTarget-1);$('#temp-target').textContent=tempTarget+'°';if(sim.state.ac)command('climate',tempTarget);};$('#temp-plus').onclick=()=>{tempTarget=Math.min(30,tempTarget+1);$('#temp-target').textContent=tempTarget+'°';if(sim.state.ac)command('climate',tempTarget);};$('#climate-on').onclick=()=>command('climate',sim.state.ac?false:tempTarget);$('#defrost').onclick=()=>openDocs('matrix');$('#sources').onclick=()=>openDocs();$('#close-dialog').onclick=()=>$('#reference-dialog').close();document.querySelectorAll('[data-doc]').forEach(b=>b.onclick=()=>openDocs(b.dataset.doc));
function download(url,name){const a=document.createElement('a');a.href=url;a.download=name;a.click();}$('#shot').onclick=()=>download(scene.renderer.domElement.toDataURL(),'togg-t10f.png');$('#export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({...sim.report(),vehicleProfile,vehicleFacts,audit,systemAudit,reviewDate,references,requirements,assumptions},null,2)],{type:'application/json'}));download(url,'ev-deney-raporu.json');setTimeout(()=>URL.revokeObjectURL(url),500);};
paintMap($('#panorama-map'));$('#cockpit-expand').onclick=()=>{const on=$('.togg-cockpit').classList.toggle('expanded');$('#cockpit-expand').title=on?'Kokpiti küçült':'Kokpiti büyüt';};$('#console-power').onclick=()=>launch(sim.state.ready?'stop':'start');$('#console-warning').onclick=()=>openDocs('matrix');$('#cockpit-reference').onclick=()=>openDocs('cockpit');selectComponent('gw');choose(0);bindRefs();let previous=performance.now();function frame(now){const dt=Math.min(.1,(now-previous)/1000);previous=now;if(playing){elapsed+=dt*rate;if(elapsed>=.85){elapsed=0;advance();}}scene.render(now,dt,sim.state);requestAnimationFrame(frame);}requestAnimationFrame(frame);
window.evDebug={sim,scene,scenarios,choose,advance,command,showPanel,get playing(){return playing}};
