export const reviewDate = '2026-09-05';
export const references = {
 glazing:{title:'AB 2021/535 · Cam silme / buğu çözme',kind:'Mevzuat',url:'https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02021R0535-20240411',section:'11.04.2024 konsolide metin · Ek IV ve VI',summary:'Ön cam yıkama/silme ve buz/buğu çözme için ayrı fiziksel gereklilikler.',limit:'Sonraki tüm değişikliklerin tarandığı iddia edilmez. Yalnız silecek komutu modellenir; buğu çözme, yıkama ve görüş alanı performans deneyleri yoktur.'},
 togg:{title:'Togg T10F · Haziran 2026 kataloğu',kind:'Üretici verisi',url:'https://trumore-cdn.togg.cloud/ToggT10FKatalog.pdf',section:'15.06.2026 · s.6,14,20,24–25 · V2 RWD Uzun Menzil',summary:'Seçili varyantın boyut, brüt kapasite, motor, şarj ve ekran referansı.',limit:'Türkiye kataloğu AB tip onayı belgesi değildir. İç ağ, ECU konumları, kablo tesisatı, gerilim ve kontrol kalibrasyonları bu kaynakla doğrulanmaz.'},
 eu858:{title:'AB 2018/858 · Tip onayı çerçevesi',kind:'Mevzuat',url:'https://eur-lex.europa.eu/eli/reg/2018/858',section:'Madde 1, 5; Ek II',summary:'Araç, sistem ve bileşen tip onayı ile piyasa gözetiminin çerçevesi.',limit:'Bu proje tip onayı dosyası veya uygunluk belgesi değildir. Araç kategorisi, üretim yolu ve başvuru tarihi için uygulanabilirlik analizi gerekir.'},
 gsr:{title:'AB 2019/2144 · Genel güvenlik',kind:'Mevzuat',url:'https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:02019R2144-20260802',section:'Madde 5–7; Ek II · 02.08.2026 konsolidasyonu incelendi',summary:'Genel güvenlik ve sürücü destek gereklilikleri; kategori ve geçiş tarihleri Ek II ile değerlendirilir.',limit:'ISA, AEB, ELKS, DDAW/ADDW, EDR ve TPMS için gerçek algılama ve homologasyon testleri bu modelde yoktur.'},
 r100:{title:'UNECE R100 · Elektrikli güç aktarma',kind:'Mevzuat',url:'https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:42024X1955',section:'03 serisi, Supplement 3 · §5.1, §5.3, Bölüm II',summary:'Elektrik güvenliği ve REESS testleri. §5.3.3: sabit şarj noktasına fiziksel bağlıyken aracın kendi tahrikiyle hareketi engellenir. §5.3.1: sürüşe hazır göstergesi.',limit:'İzolasyon, temas koruması, batarya kötüye kullanım ve su testleri yapılmaz. Buradaki davranış testleri fiziksel R100 doğrulaması değildir. Uygulanacak seri ayrıca belirlenmelidir.'},
 r155:{title:'UNECE R155 · Siber güvenlik',kind:'Mevzuat',url:'https://eur-lex.europa.eu/eli/reg/2021/387/oj/eng',section:'§7.2–7.3; Ek 5',summary:'Üretici CSMS süreçleri ve araç tipine ait risk değerlendirme, azaltım ve izleme gereklilikleri.',limit:'İzin filtresi bir tasarım seçimi; R155 belirli bir gateway, CAN kimliği veya kriptografik ürün zorunlu kılmaz. Kriptografi burada uygulanmaz.'},
 r156:{title:'UNECE R156 · Yazılım güncelleme',kind:'Mevzuat',url:'https://eur-lex.europa.eu/eli/reg/2021/388/oj/eng',section:'§7.2.1.1; §7.2.2.1–7.2.2.5',summary:'Güncelleme bütünlüğü, yeterli enerji, güvenli koşullar, kullanıcı bilgilendirmesi ve başarısızlıkta geri dönüş veya güvenli duruma geçiş.',limit:'A/B slotları bu projenin tasarım kararıdır; zorunlu tek yöntem değildir. Enerji eşiği ve imza sonucu model girdisidir; SUMS denetimi yapılmaz.'},
 r21:{title:'UNECE R21 · Elektrikli camlar',kind:'Mevzuat',url:'https://eur-lex.europa.eu/eli/reg/2008/21(2)/oj/eng',section:'§5.8.2–5.8.5 · OJ 2008 metni; sonraki değişiklikler ayrıca gerekli',summary:'Elektrikli camların kullanım koşulları ve otomatik geri açma hükümleri için başvuru kaynağı.',limit:'Engel girdisiyle yerel geri açma gösterilir. Kuvvet, açıklık geometrisi ve ölçüm düzeneği simüle edilmez; mevzuattaki fiziksel sıkışma testinden geçtiği iddia edilmez.'},
 r158:{title:'UNECE R158 · Geri manevra görüşü',kind:'Mevzuat',url:'https://eur-lex.europa.eu/eli/reg/2021/828/oj/eng',section:'OJ 2021/828 · Bölüm II · §15–17',summary:'Geri manevrada görüş veya algılama sistemleri için gereklilikler.',limit:'Bu projede kamera veri yolu ve görüntü kaybı modellenir; görüş alanı, nesne boyutu ve tepki süresi homologasyon testi yapılmaz. ABD FMVSS 111 değeri AB sınırı olarak kullanılmaz.'},
 ecall:{title:'AB 2015/758 · 112 eCall',kind:'Mevzuat',url:'https://eur-lex.europa.eu/legal-content/EN/ALL/?uri=celex:32015R0758',section:'Madde 4–6 · temel metin; değişikliklerle birlikte',summary:'M1/N1 eCall sistemi, işlevsel gerekler ve kişisel veri koruması.',limit:'PSAP ve şebeke sanaldır; gerçek 112 bağlantısı kurulmaz. Konum/kimlik verileri örnektir. eCall, OEM bulut servisinden ayrı modellenir.'},
 ecall26:{title:'AB 2025/1871 · IP tabanlı eCall',kind:'Mevzuat',url:'https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32025R1871',section:'Madde 3 · 2026 geçişi; 2017/79 değişiklikleri',summary:'01.01.2026’dan itibaren belirtilen tip onaylarında paket anahtarlamalı eCall teknik şartları; geçişte CEN/TS 17184:2022 ve 17240:2018 veya talep üzerine EN 2024 sürümleri.',limit:'2027 yeni tip ve araç tescil geçişleri de Madde 3(2–3) kapsamındadır. 2024/1180 değişikliğiyle birlikte değerlendirilir. IMS, ses kalitesi, MSD kodlaması, şebeke birlikte çalışabilirliği ve fiziksel dayanım test edilmez.'},
 zonal:{title:'NXP · Otomotiv bölge kontrol mimarisi',kind:'Teknik kaynak',url:'https://www.nxp.com/applications/AUTOMOTIVE-ZONE-CONTROLLER',section:'Zone controller reference architecture',summary:'Ethernet omurgası ile CAN/LIN ve yerel güç dağıtımını birleştiren bölge kontrol yaklaşımı.',limit:'ECU yerleri, port sayıları, kablo güzergahları ve seçilen hızlar bu proje için önerilen mimaridir; bir OEM çizimi değildir.'},
 vhal:{title:'AOSP · Vehicle HAL',kind:'Teknik kaynak',url:'https://source.android.com/docs/automotive/vhal',section:'VHAL overview / vehicle properties',summary:'Android Automotive araç özellikleri için VHAL arayüzü.',limit:'CarService/VHAL mantıksal olarak IVI içinde temsil edilir. Fiziksel SOME/IP eşlemesi OEM uygulamasına bağlıdır; örnek sinyal adları DBC/ARXML değildir.'},
 precharge:{title:'TI · Yüksek gerilim ön şarjı',kind:'Teknik kaynak',url:'https://www.ti.com/lit/ug/tiduf73/tiduf73.pdf',section:'TIDUF73 · Eylül 2024 · pasif ön şarj referans tasarımı',summary:'Ana kontaktörler, ön şarj yolu ve DC-link kapasitansından oluşan devre yaklaşımı.',limit:'Modelde 100 Ω / 2 mF RC, 400 V ve %95 eşik tasarım varsayımıdır. Direnç enerji boyutlandırması ve kontaktör donanım doğrulaması yapılmaz.'},
 ccs:{title:'CharIN · CCS teknik kaynakları',kind:'Teknik kaynak',url:'https://www.charin.global/technology/knowledge-base/',section:'CCS / IEC 61851 / ISO 15118',summary:'Şarj kontrolü ve CCS haberleşmesi için referans dokümanlar.',limit:'AC pilot ve DC PLC oturumları davranış düzeyindedir; ISO 15118 mesaj kodlayıcısı veya uygunluk test sistemi değildir. Plug & Charge destekleyen tüm araçlarda zorunlu değildir.'},
 a2b:{title:'Analog Devices · A²B ses ağı',kind:'Teknik kaynak',url:'https://www.analog.com/en/solutions/a2b-automotive-audio-bus.html',section:'Automotive Audio Bus',summary:'Çok kanallı dijital ses taşıma teknolojisi.',limit:'IVI ana düğüm, amfi alt düğüm olarak seçildi. Amfiden pasif hoparlöre giden analog güç çıkışı ayrı gösterilir; gerçek ses codec’i çalışmaz.'},
 asil:{title:'ZVEI · İşlevsel güvenlik / ASIL (NXP arşivi)',kind:'Teknik kaynak',url:'https://www.nxp.com/assets/documents/data/en/fact-sheets/FUNCTIONAL_SAFETY.pdf',section:'ZVEI, Haziran 2012 · s.5–6; ISO standardı metni değil',summary:'ASIL sınıflandırması güvenlik hedefleri ve risk değerlendirmesiyle ilişkilidir.',limit:'HARA ve tahsis edilmiş güvenlik gereksinimleri olmadan ECU’lara kesin ASIL etiketi verilmez. ISO 26262 uygunluğu iddia edilmez.'},
 r121:{title:'UNECE R121 · Kumanda ve göstergeler',kind:'Mevzuat',url:'https://eur-lex.europa.eu/eli/reg/2016/18/oj/eng',section:'01 değişiklik serisi · 2016/18 · §5; güncel seri iddiası yok',summary:'Gösterge ve kumanda tanımları için düzenleme başlığı; AB çerçevesindeki atıflarla birlikte değerlendirilmelidir.',limit:'Ekranlar HMI prototipidir. Genel arayüz ikonları R121 onaylı sembol takımı değildir. Renk, sembol, görünürlük, sürücü görüş alanı ve gündüz/gece okunabilirliği fiziksel olarak doğrulanmamıştır; uygulanacak güncel seri belirlenmelidir.'}
};
export const requirements = [
 ['R-01','Tip onayı kapsamı','eu858','M1 / AB / yeni tip varsayımı','Kapsam kaydı','Onay kuruluşu ve teknik servis değerlendirmesi'],
 ['R-02','Şarjda tahrik kilidi','r100','§5.3.3','Davranış testi','Konnektörle fiziksel hareket engelleme testi'],
 ['R-03','READY ve yön göstergesi','r100','§5.3.1, §5.3.4','Davranış testi','Araç üstünde HMI doğrulaması'],
 ['R-04','HV ve REESS güvenliği','r100','§5.1; Bölüm II','Kısmi model','İzolasyon, elektriksel/termal/mekanik ve çevresel testler'],
 ['R-05','Yetkisiz komut engelleme','r155','§7.3; Ek 5','Davranış testi','TARA, sızma testleri, CSMS ve yaşam döngüsü kanıtı'],
 ['R-06','OTA güvenli güncelleme','r156','§7.2.2','Davranış testi','SUMS, gerçek imza, enerji ve kurtarma doğrulaması'],
 ['R-07','Cam otomatik geri açma','r21','§5.8','Kısmi model','Kuvvet/konum ölçümü ve çalışma koşulları'],
 ['R-08','Geri görüş','r158','Bölüm II','Kısmi model','Görüş alanı, algılama ve tepki deneyleri'],
 ['R-09','112 eCall','ecall','Madde 4–6','Kısmi model','MSD, ses, gizlilik ve uçtan uca test'],
 ['R-10','Paket anahtarlamalı eCall','ecall26','Madde 3','Kısmi model','Uygulanabilir EN/CEN sürümü ile IMS/PSAP testi'],
 ['R-11','ISA / AEB / ELKS / sürücü izleme','gsr','Madde 6–7; Ek II','Modellenmedi','Sensörler, kontrol algoritmaları ve ilgili onay testleri'],
 ['R-12','TPMS / EDR / diğer güvenlik işlevleri','gsr','Madde 5–6; Ek II','Modellenmedi','Kapsam/tarih matrisi ve araç deneyleri'],
 ['R-13','EMC, fren, direksiyon, aydınlatma','gsr','Ek II: ilgili UN düzenlemeleri','Modellenmedi','R10, R13-H, R79, R48 ve ilgili düzenleme serilerinin analizi'],
 ['R-14','Buğu çözme / yıkama-silme','glazing','Ek IV: silme/yıkama; Ek VI: buz/buğu','Yalnız silecek komutu','Annex IV / VI fiziksel performans testleri'],
 ['R-15','Gösterge / merkezi ekran HMI','r121','Yerleşim, semboller ve görünürlük','Kısmi model','R121 sembol, renk, görüş alanı ve fiziksel okunabilirlik değerlendirmesi']
].map(([id,title,ref,section,coverage,evidence])=>({id,title,ref,section,coverage,evidence}));
export const assumptions=[
 ['A-01','Araç','Togg T10F V2 RWD Uzun Menzil; 4,830 × 1,881 × 1,556 m','Katalog ölçülerine dayalı yaklaşık dış yüzey; üretim CAD’i değil'],
 ['A-02','Enerji','89,6 kWh brüt; 160 kW motor; AC 11 / DC 180 kW azami','SOC hesabı brüt kapasite vekiliyle; net kapasite bilinmiyor. 400 V ve sabit şarj gücü model tercihi; OEM eğrisi değil'],
 ['A-03','Ön şarj','R=100 Ω, C=2 mF, Vbus/Vpack ≥ 0,95; 1,5 s timeout','RC denklemi; tasarım eşiği, yasal sınır değil'],
 ['A-04','Ağ','100BASE-T1; CAN-FD 500 kbit/s / 2 Mbit/s; LIN 19,2 kbit/s','Togg ağ topolojisi olduğu iddia edilmez; mesaj ve gecikmeler varsayım, arbitrasyon/EMI çözülmez'],
 ['A-05','Güvenlik','Başlatma için fren, anahtar, park; OTA için park ve SOC ≥ %20','Seçilen kontrol politikası; AB’nin sayısal eşikleri değil'],
 ['A-06','Dinamik','Cam 3 s; kütle 2.195 kg (katalog alt sınırı); CdA=0,588 m²','Cd=0,24 model ailesi için katalog beyanı; V2 özel ölçüm değil. Ön alan 2,45 m² varsayım. Yük, dişli oranı ve tekerlek etkin yarıçapı kalibre edilmedi'],
 ['A-07','Zaman','Kayıtta sanal ms; otomatik aktarım hedefi 850 / hız ms (2×: 425 ms); adım modu elle','Görsel yavaşlatma gerçek zaman performansı kanıtlamaz'],
 ['A-08','Fiziksel bağlantı','HV kablo çifti, CAN/LIN bus kesimleri ve LV dönüş yolu toplulaştırılmış','Pinout, kesit, sigorta kalibrasyonu ve kablo imalat listesi yok'],
 ['A-09','Kapsam','Türkçe kaynak özetleri; inceleme 05.09.2026','Yürürlükteki tüm değişiklikleri kapsayan hukuki uygunluk görüşü değil'],
 ['A-10','Politika eşikleri','SOC %5/%20/%95, sıcaklık 50/55 °C, tork timeout 100 ms','Örnek politika; yasal sınır veya ölçülmüş OEM kalibrasyonu değil'],
 ['A-11','Isı modeli','Kabin 60 kJ/K; batarya 350 kJ/K; örnek transfer katsayıları','Yığılmış model, ölçümle kalibre edilmemiştir'],
 ['A-12','HMI','12,3 / 29 / 8 inç ekran referansı; ayrı ICM ve IVI model tercihi','Özgün HMI prototipi; Togg yazılımı veya R121 doğrulanmış yerleşim değil']
];
