import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoundedBoxGeometry} from 'three/addons/geometries/RoundedBoxGeometry.js';
import {components,wires,types} from './architecture.js';
import {createT10F} from './t10f-body.js';
export function createScene(host,onSelect){
 const scene=new T.Scene();scene.background=new T.Color('#e9eef1');const renderer=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));host.appendChild(renderer.domElement);
 const camera=new T.PerspectiveCamera(36,1,.05,80);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=3;controls.maxDistance=15;controls.maxPolarAngle=Math.PI*.49;
 scene.add(new T.HemisphereLight(0xffffff,0x65777a,2.7));const sun=new T.DirectionalLight(0xffffff,2.4);sun.position.set(-4,7,5);scene.add(sun);
 const grid=new T.GridHelper(13,52,0xc9d3da,0xd8e0e5);grid.position.y=.03;scene.add(grid);
 const car=new T.Group();car.name='Togg T10F V2 RWD LR';scene.add(car);const body=createT10F(car),{shell,wheels,glasses,wiper}=body;const parts={};const labels=[];let exterior=false,follow=true,focusPending=false;const focusTarget=new T.Vector3(),focusCamera=new T.Vector3();controls.addEventListener('start',()=>{focusPending=false;});
 function box(size,pos,color,parent=car,opacity=1){const m=new T.Mesh(new RoundedBoxGeometry(...size,2,Math.min(.025,...size.map(n=>n/4))),new T.MeshStandardMaterial({color,roughness:.42,metalness:.2,transparent:opacity<1,opacity,depthWrite:opacity===1}));m.position.set(...pos);parent.add(m);return m;}
 for(const c of components){const mesh=box(c.size,c.pos,types[c.type].color,car,c.id==='battery'?.24:1);mesh.userData.id=c.id;parts[c.id]=mesh;mesh.name=c.tag;mesh.add(new T.LineSegments(new T.EdgesGeometry(mesh.geometry),new T.LineBasicMaterial({color:0xffffff,transparent:true,opacity:.4})));const el=document.createElement('button');el.className='part-label';el.textContent=c.tag;el.title=c.name;el.onclick=()=>onSelect(c.id);host.appendChild(el);labels.push({c,el});}
 const curves={};let exploded=0,layer='network',selected='gw',active=null,activeStart=0,labelsOn=true,allLabels=false;
 function route(w){const a=parts[w.from].position.clone(),b=parts[w.to].position.clone();let pts;if(w.wireless||['signal','lin','a2b'].includes(w.type))pts=[a,a.clone().lerp(b,.5).add(new T.Vector3(0,.04,0)),b];else{const z=w.type==='hv'?.55:w.type==='lv'?-.55:w.type==='thermal'?.65:0,y=.56+(w.type==='eth'?.04:0);pts=[a,new T.Vector3(a.x,y,a.z),new T.Vector3(a.x,y,z),new T.Vector3(b.x,y,z),new T.Vector3(b.x,y,b.z),b];}pts=pts.filter((p,i)=>i===0||p.distanceTo(pts[i-1])>.001);return new T.CatmullRomCurve3(pts,false,'centripetal');}
 for(const w of wires){const curve=route(w),mesh=new T.Mesh(new T.TubeGeometry(curve,48,w.type==='hv'?.014:.009,5,false),new T.MeshBasicMaterial({color:types[w.type].color,transparent:true,opacity:.65}));car.add(mesh);curves[w.id]={curve,mesh,w};}
 const packet=new T.Mesh(new T.SphereGeometry(.043,12,12),new T.MeshBasicMaterial({color:0x1a745d}));car.add(packet);packet.visible=false;packet.add(new T.Mesh(new T.SphereGeometry(.09,12,12),new T.MeshBasicMaterial({color:0x59c69d,transparent:true,opacity:.25})));
 const cuts=new Set(),offline=new Set();
 function refresh(){for(const c of components){const p=parts[c.id];p.visible=!exterior;const hi=c.id===selected||active?.from===c.id||active?.to===c.id;p.material.emissive.set(offline.has(c.id)?0x9e3434:hi?types[c.type].color:0);p.material.emissiveIntensity=hi?.35:.08;const involved=active&&(active.from===c.id||active.to===c.id),dim=active&&!involved;p.material.opacity=dim?.13:c.id==='battery'?(involved?.8:layer==='power'?.65:.16):offline.has(c.id)?.28:1;const transparent=p.material.opacity<1;if(p.material.transparent!==transparent){p.material.transparent=transparent;p.material.needsUpdate=true;}p.material.depthWrite=!transparent;}for(const {mesh,w} of Object.values(curves)){const matches=layer==='all'||(layer==='network'&&!['power','thermal'].includes(types[w.type].kind))||(layer==='power'&&types[w.type].kind==='power')||(layer==='thermal'&&w.type==='thermal')||layer===w.type;const live=active?.edge===w.id;mesh.visible=!exterior&&(matches||live);mesh.material.color.set(cuts.has(w.id)?'#cc354b':types[w.type].color);mesh.material.opacity=live?1:active?.07:cuts.has(w.id)?.85:(w.from===selected||w.to===selected)?.95:matches?.52:.08;}}
 function size(){const {width,height}=host.getBoundingClientRect();renderer.setSize(width,height);camera.aspect=width/height;camera.updateProjectionMatrix();}new ResizeObserver(size).observe(host);
 const ray=new T.Raycaster();let down;renderer.domElement.addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;const r=host.getBoundingClientRect();ray.setFromCamera(new T.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);const hit=ray.intersectObjects(Object.values(parts),false)[0];if(hit)onSelect(hit.object.userData.id);});
 const rings=Array.from({length:3},()=>{const r=new T.Mesh(new T.TorusGeometry(.14,.007,6,40),new T.MeshBasicMaterial({color:0x237cc6,transparent:true}));r.rotation.x=Math.PI/2;car.add(r);return r;});
 function home(top=false){focusPending=false;camera.position.set(...(top?[0,8,.01]:[-4.5,3.6,5]));controls.target.set(0,.9,0);controls.update();}home();size();refresh();
 return {scene,renderer,camera,parts,controls,curves,select(id){selected=id;refresh();},setEvent(e){active=e?.edge?e:null;activeStart=performance.now();focusPending=!!active&&follow;if(focusPending){const a=parts[active.from].position,b=parts[active.to].position;focusTarget.copy(a).lerp(b,.5);const distance=T.MathUtils.clamp(a.distanceTo(b)*1.15+2.6,3.2,7.5),direction=camera.position.clone().sub(controls.target).normalize();focusCamera.copy(focusTarget).addScaledVector(direction,distance);}refresh();},setFollow(v){follow=v;if(!v)focusPending=false;},setLayer(v){layer=v;refresh();},setLabels(v,all=false){labelsOn=v;allLabels=all;},setBody(v){shell.visible=v;},setExterior(v){exterior=v;shell.visible=true;body.setExterior(v);refresh();},home,
  setFaults(c,o){cuts.clear();c.forEach(x=>cuts.add(x));offline.clear();o.forEach(x=>offline.add(x));refresh();},
  setExplode(v){exploded=v;for(const c of components)parts[c.id].position.y=c.pos[1]+(c.external?0:v*(c.id==='battery'?-.12:.65));for(const c of Object.values(curves)){c.curve=route(c.w);c.mesh.geometry.dispose();c.mesh.geometry=new T.TubeGeometry(c.curve,48,c.w.type==='hv'?.014:.009,5,false);}},
  render(now,dt,state){if(focusPending&&follow&&!exterior){const alpha=1-Math.exp(-dt*2.8);controls.target.lerp(focusTarget,alpha);camera.position.lerp(focusCamera,alpha);}controls.update();for(const w of wheels)w.rotation.z-=state.speed*dt*.08;glasses.forEach((g,i)=>{const target=-(i===0?state.window:0)*.42;g.position.y+=(target-g.position.y)*Math.min(1,dt*5);});wiper.rotation.x=state.wiper?Math.sin(now*.005)*.65:0;parts.lights.material.emissiveIntensity=state.lights?1.1:.05;
   rings.forEach((r,i)=>{r.visible=state.lte&&!exterior;const phase=(now*.0006+i/3)%1;r.position.copy(parts.antenna.position);r.position.y+=.1+phase*.2;r.scale.setScalar(1+phase*2);r.material.opacity=1-phase;});
   packet.visible=!!active&&!active.failed&&!exterior;if(packet.visible){const c=curves[active.edge],u=T.MathUtils.clamp((now-activeStart)/650,0,1);packet.position.copy(c.curve.getPointAt(c.w.from===active.from?u:1-u));packet.material.color.set(types[c.w.type].color);}
   const rect=host.getBoundingClientRect(),placed=[];const display=labels.filter(({c})=>labelsOn&&!exterior&&(allLabels||c.id===selected||c.id===active?.from||c.id===active?.to||['gw','bcm','screen','cluster','bms','tcu','inverter','port'].includes(c.id)));
   labels.forEach(l=>l.el.hidden=true);for(const {c,el} of display){const p=parts[c.id].position.clone();p.y+=c.size[1]/2+.065;p.project(camera);if(p.z>1||Math.abs(p.x)>1||Math.abs(p.y)>1)continue;el.hidden=false;el.style.opacity=active&&c.id!==active.from&&c.id!==active.to?'.25':'1';el.classList.toggle('active',c.id===active?.from||c.id===active?.to);const width=el.offsetWidth,height=el.offsetHeight;let x=Math.max(width/2+8,Math.min(rect.width-width/2-8,(p.x*.5+.5)*rect.width)),y=(-p.y*.5+.5)*rect.height;for(let n=0;n<18;n++){const q=placed.find(q=>Math.abs(q.x-x)<(q.w+width)/2+5&&Math.abs(q.y-y)<height+5);if(!q)break;y=q.y-height-6;}if(y<height+8){el.hidden=true;continue;}el.style.left=x+'px';el.style.top=y+'px';placed.push({x,y,w:width});}renderer.render(scene,camera);
  },stats(){return {vehicle:'Togg T10F',dimensions:body.dimensions,exterior,follow,focusPending,active:active?.edge,layer,exploded,parts:components.length,links:wires.length};}
 };
}
