import {byId,wires,link,pt,ch} from './architecture.js';
import {vehicleProfile} from './vehicle-profile.js';
export const parameters={vehicle:vehicleProfile,capacityBasis:'gross-proxy-not-usable',capacityKWh:vehicleProfile.grossCapacityKWh,maxPowerKW:vehicleProfile.maxPowerKW,acMaxKW:vehicleProfile.acMaxKW,dcMaxKW:vehicleProfile.dcMaxKW,voltage:400,prechargeR:100,dcLinkC:.002,prechargeRatio:.95,prechargeTimeout:1500,mass:2195,cdA:.588,rolling:.012,airDensity:1.225,windowTravelMs:3000};
export const initialState=()=>({soc:72,temp:28,cabin:28,targetTemp:22,speed:0,power:0,voltage:400,busV:0,hv:false,ready:false,plug:false,charging:false,chargeContactor:false,precharge:false,locked:true,window:0,windowTarget:0,windowReported:0,windowDirection:0,lte:false,phone:false,music:false,ac:false,cooling:false,lights:false,wiper:false,camera:false,mode:'PARK',media:'Medya kapalı',fault:'',keyAuthorized:true,brake:true,park:true,authorized:true,main12:true,backup:true,network:true,isolation:true,obstruction:false,prechargeIntact:true,updateAuthentic:true,updateBootOK:true,ota:'3.4.1',slot:'A',staged:false,ecall:'Beklemede',chime:false,reportedCabin:28,chargeLimit:180,dischargeLimitKW:null,torqueLimitNm:350,readyIndication:false,command:'',gear:'P'});
const message=(route,bus,signal,value,extra={})=>({kind:'message',route,bus,signal,value,...extra});
const check=(rule,label,ref)=>({kind:'check',rule,label,ref});
const action=(op,label,extra={})=>({kind:'action',op,label,...extra});
const wait=(ms,label)=>({kind:'wait',ms,label});
const power=(route,label,extra={})=>({kind:'power',route,bus:'hv',signal:label,...extra});
const req=(node,signal,value)=>message(['screen','gw',node],'eth',signal,value);
const ack=(node,signal,value,extra={})=>message([node,'gw','screen'],'eth',signal,value,extra);
const ready={hv:true,ready:true,busV:400,readyIndication:true,mode:'READY'};
const startup=[message(['key','bcm'],'signal','KeyAuthorization','request'),check('start','Anahtar, fren, park ve şarj kilidi','r100'),message(['bcm','gw'],'eth','StartRequest',true),message(pt('gw','bms'),'can','EnergyEnable','request'),message(['battery','bms'],'signal','CellMeasurements','read'),message(['imd','bms'],'signal','IsolationStatus','read'),check('battery','BMS enerji izni','r100'),message(['bms','pdu'],'signal','PrechargeRequest',true,{effect:'precharge'}),wait(700,'RC ön şarjının ilerlemesi'),check('precharge','DC-link gerilimi / kontaktör geri bildirimi','precharge'),message(['bms','pdu'],'signal','MainContactors','close',{effect:'hvOn'}),message(pt('bms','vcu'),'can','HVReady',true,{effect:'ready'}),message(pt('vcu','gw'),'can','DriveState','READY'),message(['gw','cluster'],'eth','ReadyIndication',true,{effect:'readyIndication'}),power(['battery','pdu','dcdc'],'12 V ağına enerji'),action('dcdc','DC/DC çalışıyor')];
const windowCommand=(target)=>[message(['screen','gw'],'eth','WindowPositionRequest',target),check('windowPermission','Gateway cam kontrol yetkisi','r155'),message(['gw','bcm'],'eth','WindowPositionRequest',target),message(['bcm','window'],'lin','WindowTarget',target,{effect:'windowTarget'}),wait(3000,'Yerel motor hareketi / Hall geri bildirimi'),message(['window','bcm'],'lin','WindowPosition','actual'),ack('bcm','WINDOW_POS','actual',{effect:'reportWindow'})];
const lte=[action('tcuWake','Telematik uyanma'),message(['tcu','antenna','cloud'],'rf','NetworkRegistration','LTE/IP'),check('network','Hücresel oturum erişimi','ecall26'),message(['cloud','antenna','tcu'],'rf','RegistrationAccepted',true,{effect:'lte'}),message(['tcu','gw','screen'],'eth','Connectivity','connected')];
// Cross-domain messages are explicitly routed via the selected network, never via power wires.
const hvacRequest=[message(['screen','gw'],'eth','HVAC_TEMPERATURE_SET',22),check('authorized','Konfor kontrol yetkisi','r155'),message(pt('gw','hvac'),'can','CabinTarget',22,{effect:'cabinTarget'}),check('hvac','Kompresör HV ve LV beslemesi','r100'),power(['battery','pdu','hvac'],'Kompresör beslemesi'),message(['gw','zfr'],'eth','CoolingRequest',true),message(['zfr','pump'],'lin','PumpEnable',true,{effect:'cooling'}),action('acOn','Kabin sıcaklık denetimi'),wait(5000,'Kabin enerji dengesi'),message(pt('hvac','gw'),'can','CabinTemperature','actual'),message(['gw','screen'],'eth','HVAC_TEMPERATURE_CURRENT','actual',{effect:'reportCabin'})];
export const scenarios=[
 {id:'start',name:'Aracı çalıştır',group:'Sürüş',icon:'power',refs:['r100','precharge','zonal'],steps:startup},
 {id:'drive',name:'Gaz / tork isteği',group:'Sürüş',icon:'gauge',refs:['r100'],initial:ready,steps:[check('drive','Tahrik izni ve soket kilidi','r100'),message(pt('vcu','inverter'),'can','TorqueRequest',120),power(['battery','pdu','inverter','motor'],'Pozitif tork enerjisi'),action('accelerate','Tork uygulanıyor'),wait(5000,'Boylamsal hareket'),message(ch('abs','gw'),'can','VehicleSpeed','actual'),message(['gw','cluster'],'eth','SpeedDisplay','actual')]},
 {id:'regen',name:'Rejeneratif fren',group:'Sürüş',icon:'battery-charging',refs:['r100'],initial:{...ready,speed:60,park:false,gear:'D'},steps:[message(ch('abs','vcu'),'can','BrakeRequest',true),check('regen','BMS geri kazanım sınırı','r100'),message(pt('vcu','inverter'),'can','NegativeTorque',-70),power(['motor','inverter','pdu','battery'],'Bataryaya geri kazanım'),action('regen','Negatif tork'),wait(3500,'Frenleme ve enerji hesabı'),message(pt('bms','gw'),'can','SOC','actual'),message(['gw','cluster'],'eth','EnergyDisplay','actual')]},
 {id:'stop',name:'Aracı kapat',group:'Sürüş',icon:'circle-stop',refs:['r100'],initial:ready,steps:[check('park','Hız sıfır / P konumu','r100'),message(pt('vcu','inverter'),'can','TorqueRequest',0,{effect:'zeroTorque'}),message(pt('vcu','bms'),'can','ShutdownRequest',true),message(['bms','pdu'],'signal','MainContactors','open',{effect:'hvOff'}),wait(2000,'DC-link boşalma modeli'),message(['gw','cluster'],'eth','DriveState','OFF',{effect:'sleep'})]},
 {id:'accharge',name:'AC şarj',group:'Enerji',icon:'plug',refs:['r100','ccs'],steps:[action('plug','AC konnektör takıldı'),message(['evse','evcc'],'pilot','CP_State','B → C'),message(pt('evcc','bms'),'can','ChargePermission','AC'),check('charge','BMS şarj koşulları','r100'),message(pt('bms','obc'),'can','ACCurrentLimit',16),power(['evse','port','obc','battery'],'AC → OBC → DC'),action('chargeAC','OBC şarjı etkin'),wait(5000,'Enerji aktarımı'),message(pt('bms','gw'),'can','ChargeState','AC'),message(['gw','cluster'],'eth','ChargingDisplay','AC')]},
 {id:'dccharge',name:'DC hızlı şarj',group:'Enerji',icon:'zap',refs:['r100','ccs'],steps:[action('plug','DC konnektör takıldı'),message(['evse','evcc'],'pilot','PLC Session','CCS'),message(pt('evcc','bms'),'can','ChargePermission','DC'),check('charge','BMS ve şarj sınırları','r100'),message(['bms','charge'],'signal','DCContactors','close',{effect:'dcContactor'}),power(['evse','port','charge','battery'],'OBC dışında DC yolu'),action('chargeDC','DC enerji aktarımı'),wait(5000,'Enerji aktarımı'),message(pt('bms','gw'),'can','ChargeState','DC'),message(['gw','cluster'],'eth','ChargingDisplay','DC')]},
 {id:'unplug',name:'Şarjı durdur / ayır',group:'Enerji',icon:'unplug',refs:['r100','ccs'],initial:{plug:true,charging:true,chargeContactor:true,power:-50,mode:'DC ŞARJ'},steps:[message(['screen','gw'],'eth','StopCharge',true),message(pt('gw','evcc'),'can','StopCharge',true),message(['evcc','evse'],'pilot','CurrentDemand',0,{effect:'stopCharge'}),check('zeroCurrent','Enerji aktarımı sıfır','ccs'),message(pt('evcc','bms'),'can','DisconnectCharge',true),message(['bms','charge'],'signal','DCContactors','open',{effect:'dcOff'}),action('unplug','Port kilidi açıldı; konnektör ayrıldı')]},
 {id:'thermal',name:'Batarya termal yönetimi',group:'Enerji',icon:'thermometer',refs:['r100'],initial:{...ready,temp:43},steps:[message(['battery','bms'],'signal','PackTemperature','actual'),message(pt('bms','gw'),'can','CoolingDemand',true),message(['gw','zfr'],'eth','PumpRequest',true),message(['zfr','pump'],'lin','PumpSpeed',70,{effect:'cooling'}),action('thermal','Soğutma devresi etkin'),wait(10000,'Yığılmış termal model'),message(['battery','bms'],'signal','PackTemperature','actual')]},
 {id:'low',name:'Düşük SOC / güç sınırı',group:'Enerji',icon:'battery-low',refs:['r100'],initial:{...ready,soc:8},steps:[message(pt('bms','vcu'),'can','DischargeLimit',15,{effect:'lowSOC'}),message(pt('vcu','inverter'),'can','TorqueLimit',30,{effect:'torqueLimit'}),message(pt('vcu','gw'),'can','PowerLimited',true),message(['gw','cluster'],'eth','LowBatteryWarning',true)]},
 {id:'isolation',name:'İzolasyon arızası',group:'Güvenlik',icon:'shield-alert',refs:['r100'],initial:ready,steps:[action('isolationFault','IMD arıza girdisi'),message(['imd','bms'],'signal','IsolationStatus',false),message(pt('bms','vcu'),'can','HVFault',true,{effect:'zeroTorque'}),message(['bms','pdu'],'signal','EmergencyOpen',true,{effect:'hvOff'}),message(pt('bms','gw'),'can','IsolationWarning',true),message(['gw','cluster'],'eth','FaultDisplay','İzolasyon arızası')]},
 {id:'lte',name:'LTE / veri bağlantısı',group:'Bağlantı',icon:'radio-tower',refs:['zonal','r155'],steps:lte},
 {id:'phone',name:'Telefon eşleştirme',group:'Bağlantı',icon:'smartphone',refs:['vhal'],steps:[message(['phone','screen'],'rf','BluetoothPairRequest',true),check('authorized','Kullanıcı eşleştirme onayı','r155'),message(['screen','phone'],'rf','PairAccepted',true,{effect:'pair'}),message(['phone','screen'],'rf','MediaProfile','ready')]},
 {id:'music',name:'Medya / ses zinciri',group:'Bağlantı',icon:'music-2',refs:['a2b','vhal'],initial:{phone:true},steps:[check('phone','Telefon bağlı','vhal'),message(['phone','screen'],'rf','AudioStream','PCM'),message(['screen','audio'],'a2b','AudioSlots','stereo'),message(['audio','speaker'],'a2b','AnalogAudio','output',{effect:'music'})]},
 {id:'nav',name:'Navigasyon / konum',group:'Bağlantı',icon:'navigation',refs:['vhal','zonal'],steps:[...lte,message(['antenna','tcu'],'rf','GNSSFix','örnek konum'),message(['tcu','gw','screen'],'eth','Location','örnek konum'),action('navigation','Örnek rota gösterimi')]},
 {id:'unlock',name:'Telefondan kilit aç',group:'Konfor',icon:'lock-keyhole',refs:['r155','zonal'],steps:[message(['phone','cloud'],'rf','RemoteUnlock','request'),message(['cloud','antenna','tcu'],'rf','RemoteCommand','unlock'),check('authorized','Uzak komut yetkisi / tazeliği','r155'),message(['tcu','gw','bcm'],'eth','UnlockRequest',true),message(['bcm','lock'],'signal','Unlock',true,{effect:'unlock'}),ack('bcm','DoorLockStatus','unlocked')]},
 {id:'window',name:'Cam aç / kapat',group:'Konfor',icon:'panel-top',refs:['r21','vhal','zonal'],steps:[...windowCommand(1),...windowCommand(0)]},
 {id:'pinch',name:'Cam sıkışma / yerel geri açma',group:'Güvenlik',icon:'hand',refs:['r21'],initial:{window:1,windowTarget:1,windowReported:1,obstruction:true},steps:windowCommand(0)},
 {id:'hvac',name:'Kabin kliması',group:'Konfor',icon:'snowflake',refs:['zonal','r100'],initial:ready,steps:hvacRequest},
 {id:'reverse',name:'Geri görüş / R',group:'Sürüş',icon:'video',refs:['r158','r100'],initial:ready,steps:[check('drive','Sürüş izni','r100'),message(pt('vcu','gw'),'can','GearPosition','R',{effect:'reverse'}),message(['gw','cluster'],'eth','GearDisplay','R'),message(['gw','screen'],'eth','ReverseCameraRequest',true),message(['camera','screen'],'eth','VideoStream','frame',{effect:'camera'})]},
 {id:'crash',name:'Çarpışma / bağımsız eCall',group:'Güvenlik',icon:'siren',refs:['ecall','ecall26','r100'],initial:ready,steps:[action('crash','SRS çarpışma girdisi'),message(['airbag','pdu'],'signal','CrashDisconnect',true,{effect:'hvOff'}),message(['airbag','tcu'],'signal','EmergencyTrigger',true,{effect:'ecallTrigger'}),action('lvLoss','Ana 12 V kaybı'),check('backup','Acil sistem rezerv beslemesi','ecall'),message(['tcu','antenna','psap'],'rf','IMS eCall + MSD','örnek veri',{effect:'ecallConnected'}),message(['tcu','ecallspeaker'],'signal','EmergencyAudio','voice',{effect:'ecallAudio'})]},
 {id:'blocked',name:'Yetkisiz IVI komutu',group:'Güvenlik',icon:'shield-x',refs:['r155'],initial:{authorized:false},expected:'rejected',steps:[message(['screen','gw'],'eth','RawChassisWrite','örnek istek'),check('rawChassis','Gateway izin politikası','r155'),message(ch('gw','eps'),'can','SteeringCommand','yasak')]},
 {id:'ota',name:'OTA / doğrulama / geri dönüş',group:'Bağlantı',icon:'download',refs:['r156','r155'],steps:[message(['cloud','antenna','tcu'],'rf','UpdateManifest','3.5.0'),check('updateAuthentic','Güncelleme özgünlüğü / bütünlüğü','r156'),message(['tcu','gw'],'eth','UpdateRequest','ZC-RL'),message(pt('gw','bms'),'can','EnergyBudget','request'),message(pt('bms','gw'),'can','EnergyBudget','actual'),check('ota','Park, enerji ve kullanıcı onayı','r156'),message(['gw','zrl'],'eth','StageImage','slot B',{effect:'stageOTA'}),wait(8000,'Örnek imaj aktarımı'),action('activateOTA','A/B aktivasyon ve sağlık kontrolü'),message(['zrl','gw','tcu'],'eth','UpdateResult','actual'),message(['tcu','antenna','cloud'],'rf','CampaignReport','actual')]},
 {id:'precondition',name:'Uzaktan ön koşullandırma',group:'Konfor',icon:'fan',refs:['r155','r100'],steps:[message(['phone','cloud','antenna','tcu'],'rf','RemotePrecondition',22),check('authorized','Uzak komut yetkisi','r155'),...startup,...hvacRequest]},
 {id:'body',name:'Far / silecek',group:'Konfor',icon:'lightbulb',refs:['gsr','zonal'],steps:[req('zfr','LightingRequest',true),check('authorized','Gövde kontrol izni','r155'),message(['zfr','lights'],'lin','LowBeam',true,{effect:'lights'}),message(['lights','zfr'],'lin','LampStatus',true),req('zfr','WiperRequest',true),message(['zfr','wiper'],'lin','WiperSpeed',1,{effect:'wiper'}),ack('zfr','BodyStatus','active')]}
];
export class Simulation {
 constructor(){this.cuts=new Set();this.offline=new Set();this.reset(0);}
 reset(index=0,{preserve=false,inputs={}}={}){this.scenario=scenarios[index];this.scenarioIndex=index;this.state={...(preserve?this.state:initialState()),...(!preserve?this.scenario.initial:{}),...inputs,command:''};if(!preserve)this.reportCluster();this.initialSnapshot=structuredClone(this.state);this.queue=this.expand(this.scenario.steps);this.cursor=0;this.time=0;this.trace=[];this.active=null;this.status='idle';this.failure=null;this.energyWh=0;this.windowHistory=[];this.emit('INIT',null,this.scenario.name,'Başlangıç koşulları yüklendi');}
 reportCluster(){const s=this.state;s.display={speed:s.speed,soc:s.soc,temp:s.temp,gear:s.gear,power:s.power,busV:s.busV,mode:s.mode,fault:s.fault,ready:s.readyIndication};}
 expand(steps){return steps.flatMap((s,stepIndex)=>{if(!['message','power'].includes(s.kind))return [{...s,stepIndex}];return s.route.slice(1).map((to,i)=>{const from=s.route[i],w=link(from,to,s.bus);if(!w)throw new Error(`Tanımsız bağlantı: ${from} → ${to} / ${s.bus}`);return {...s,from,to,edge:w.id,stepIndex,effect:i===s.route.length-2?s.effect:null,last:i===s.route.length-2};});});}
 emit(status,event,signal,detail){this.trace.push({seq:this.trace.length,time:this.time,status,edge:event?.edge,from:event?.from,to:event?.to,bus:event?.bus,signal,value:event?.value,detail,ref:event?.ref});}
 powered(id,visited=new Set()){
  if(this.offline.has(id))return false;if(!byId[id]||byId[id].external||byId[id].bus)return true;
  if(id==='aux')return this.state.main12;if(id==='backup')return this.state.backup;
  if(['battery','pdu','charge','motor','speaker','port'].includes(id))return true;
  if(id==='antenna')return this.powered('tcu');if(id==='ecallspeaker')return this.powered('tcu')&&this.state.backup;
  if(visited.has(id))return false;visited.add(id);
  return wires.filter(w=>w.type==='lv'&&w.to===id&&!this.cuts.has(w.id)).some(w=>this.powered(w.from,new Set(visited)));
 }
 available(e){const w=wires.find(w=>w.id===e.edge);return !this.cuts.has(e.edge)&&this.powered(e.from)&&this.powered(e.to)&&!(w?.wireless&&['cloud','psap'].some(n=>n===e.from||n===e.to)&&!this.state.network);}
 fail(reason,e,status='TIMEOUT'){this.status='failed';this.failure=reason;this.state.fault=reason;this.emit(status,e,e?.signal||e?.label,reason);this.active=e?.edge?{...e,failed:true}:null;this.state.precharge=false;if(this.scenario.id==='start'||this.scenario.id==='precondition'){this.state.hv=false;this.state.ready=false;this.state.power=0;}if(this.state.staged){this.state.staged=false;this.state.mode='PARK';this.emit('RECOVERY',e,'OTA','Önceki slot korunuyor');}}
 guard(rule){const s=this.state;const rules={start:[s.keyAuthorized&&s.brake&&s.park&&!s.plug,'Başlatma engellendi: anahtar / fren / park / şarj soketi'],battery:[s.isolation&&s.soc>5&&s.temp<55,'BMS enerji izni reddedildi'],precharge:[s.busV>=s.voltage*parameters.prechargeRatio,'Ön şarj zaman aşımı / DC-link yetersiz'],drive:[s.hv&&s.ready&&!s.plug&&s.isolation&&!s.staged,'Tahrik engellendi: READY / HV / soket / güncelleme'],park:[Math.abs(s.speed)<.1&&s.park,'Kapatma engellendi: araç parkta değil'],regen:[s.soc<95&&s.temp<50&&s.hv,'Rejenerasyon sınırlandı: batarya kabul koşulları'],charge:[s.plug&&s.isolation&&s.soc<100&&s.temp<50&&Math.abs(s.speed)<.1,'Şarj izni reddedildi'],zeroCurrent:[!s.charging&&Math.abs(s.power)<.1,'Port açılamaz: enerji aktarımı sürüyor'],windowPermission:[s.authorized,'Cam komutu reddedildi: yetki yok'],authorized:[s.authorized,'Komut reddedildi: yetki / onay / tazelik'],network:[s.network,'Hücresel erişim yok'],phone:[s.phone,'Eşleştirilmiş telefon yok'],hvac:[s.hv&&this.powered('hvac'),'Klima engellendi: HV / 12 V yok'],backup:[s.backup&&this.powered('tcu'),'eCall rezerv beslemesi yok'],rawChassis:[false,'Gateway: IVI kaynağından şasi komutu yasak'],updateAuthentic:[s.updateAuthentic,'Güncelleme bütünlük / özgünlük kontrolü başarısız'],ota:[s.park&&Math.abs(s.speed)<.1&&s.soc>=20&&s.authorized&&s.main12,'OTA ön koşulları sağlanmadı']};return rules[rule]||[false,'Tanımsız kural'];}
 effect(op,value){const s=this.state;switch(op){
 case 'precharge':s.precharge=true;s.busV=0;break;case 'hvOn':s.hv=true;s.precharge=false;s.busV=s.voltage;break;case 'ready':s.ready=true;s.mode='READY';break;case 'readyIndication':s.readyIndication=true;break;
 case 'hvOff':s.hv=false;s.precharge=false;s.ready=false;s.readyIndication=false;s.power=0;s.ac=false;s.mode=s.fault?'ARIZA':'PARK';break;
 case 'dcdc':s.power=.35;break;case 'zeroTorque':s.torque=0;s.power=0;break;case 'sleep':s.mode='UYKU';break;
 case 'accelerate':s.torque=120;s.park=false;s.mode='D';s.gear='D';break;case 'regen':s.torque=-70;s.mode='REJEN';break;
 case 'plug':if(Math.abs(s.speed)>.1){this.fail('Hareket halinde şarj bağlantısı reddedildi',null,'REJECT');break;}s.plug=true;s.ready=false;s.torque=0;break;
 case 'chargeAC':s.charging=true;s.power=-parameters.acMaxKW*.95;s.mode='AC ŞARJ';break;case 'dcContactor':s.chargeContactor=true;break;case 'chargeDC':s.charging=true;s.power=-Math.min(parameters.dcMaxKW,s.chargeLimit);s.mode='DC ŞARJ';break;
 case 'stopCharge':s.charging=false;s.power=0;break;case 'dcOff':s.chargeContactor=false;break;case 'unplug':s.plug=false;s.mode='PARK';break;
 case 'cooling':s.cooling=true;break;case 'thermal':s.cooling=true;s.power=.4;break;case 'torqueLimit':s.torqueLimitNm=Number(value);break;case 'lowSOC':s.dischargeLimitKW=15;s.fault='Düşük SOC: örnek güç sınırlaması';break;case 'isolationFault':s.isolation=false;s.fault='HV izolasyon arızası';break;
 case 'tcuWake':break;case 'lte':s.lte=true;s.media='LTE bağlı';break;case 'pair':s.phone=true;s.media='Telefon bağlı';break;case 'music':s.music=true;s.media='Elektrik · örnek parça';break;case 'navigation':s.media='Rota aktif · örnek konum';break;case 'unlock':s.locked=false;break;
 case 'windowTarget':s.windowTarget=Math.max(0,Math.min(1,Number(value)));s.windowDirection=Math.sign(s.windowTarget-s.window);break;case 'reportWindow':s.windowReported=s.window;break;
 case 'cabinTarget':s.targetTemp=Number(value);break;case 'acOn':s.ac=true;s.cooling=true;s.power=2.4;break;case 'acOff':s.ac=false;s.power=s.ready?.35:0;break;case 'reportCabin':s.reportedCabin=s.cabin;break;
 case 'reverse':s.gear='R';s.mode='R';break;case 'camera':s.camera=true;s.media='Geri görüş';break;
 case 'crash':s.fault='Çarpışma olayı';s.speed=0;s.torque=0;s.mode='ACİL';break;case 'ecallTrigger':s.ecall='Tetiklendi';break;case 'lvLoss':s.main12=false;break;case 'ecallConnected':s.ecall='PSAP oturumu';s.lte=true;break;case 'ecallAudio':s.ecall='MSD + ses';break;
 case 'stageOTA':s.staged=true;s.mode='GÜNCELLEME';s.ready=false;break;case 'activateOTA':if(!this.powered('zrl')||!this.circuit(['gw','zrl'],'eth')){this.fail('OTA aktivasyonu başarısız: hedef düğüm erişilemiyor',null);break;}if(s.updateBootOK){s.slot=s.slot==='A'?'B':'A';s.ota='3.5.0';}else {s.fault='Yeni slot sağlık kontrolü başarısız';this.emit('RECOVERY',null,'OTA','Önceki sürüme geri dönüldü');}s.staged=false;s.mode='PARK';break;
 case 'lights':s.lights=true;break;case 'wiper':s.wiper=true;break;case 'lightsOff':s.lights=false;break;case 'wiperOff':s.wiper=false;break;case 'lock':s.locked=true;break;
 default:if(op)throw new Error('Tanımsız etki '+op);
 }}
 integrate(ms){const s=this.state;let left=ms;while(left>0){const dt=Math.min(left,20)/1000;left-=dt*1000;
  if(s.precharge&&s.prechargeIntact&&this.circuit(['battery','pdu','inverter'],'hv'))s.busV=s.voltage-(s.voltage-s.busV)*Math.exp(-dt/(parameters.prechargeR*parameters.dcLinkC));else if(!s.hv&&!s.precharge)s.busV*=Math.exp(-dt/.6);
  if(this.powered('window')){const d=s.windowTarget-s.window;if(Math.abs(d)>1e-5){s.window+=Math.sign(d)*Math.min(Math.abs(d),dt/(parameters.windowTravelMs/1000));if(s.obstruction&&s.windowTarget===0&&s.window<=.45){s.windowTarget=.9;s.windowDirection=1;s.fault='Cam engeli: yerel geri açma';this.emit('LOCAL',null,'AntiPinch','Motor düğümü: üst ağdan bağımsız geri açma');}}}this.windowHistory.push(s.window);
  if(s.speed>0||(s.hv&&!s.plug&&s.ready&&s.torque)){let v=s.speed/3.6;const requestedTorque=s.hv&&!s.plug&&s.ready?(s.torque||0):0,torque=Math.max(-vehicleProfile.maxTorqueNm,Math.min(vehicleProfile.maxTorqueNm,s.torqueLimitNm,requestedTorque)),powerLimit=Math.min(parameters.maxPowerKW,Math.max(0,(s.dischargeLimitKW??Infinity)-.35)*.9),force=torque>0?Math.min(torque*9/.32,powerLimit*1000/Math.max(v,.1)):torque*9/.32,drag=.5*parameters.airDensity*parameters.cdA*v*v+parameters.mass*9.81*parameters.rolling;v=Math.max(0,v+(force-drag)/parameters.mass*dt);s.speed=v*3.6;const wheel=force*v/1000;if(force)s.power=wheel>0?Math.min(s.dischargeLimitKW??Infinity,parameters.maxPowerKW/.9+.35,wheel/.9+.35):Math.max(-50,wheel*.75);}
  const wh=s.power*1000*dt/3600;this.energyWh+=wh;s.soc=Math.max(0,Math.min(100,s.soc-wh/(parameters.capacityKWh*10)));
  // Lumped heat capacities and heat transfer are declared model parameters, not measured vehicle data.
  s.temp+=(Math.abs(s.power)*.018-(s.cooling?1.2:0)-.02*(s.temp-25))*dt/350;
  s.cabin+=((28-s.cabin)*.07-(s.ac?Math.max(0,s.cabin-s.targetTemp)*.6:0))*dt/60;
  if(s.soc===100&&s.charging){s.charging=false;s.power=0;}if(s.soc===0){s.ready=false;s.hv=false;s.torque=0;s.power=0;}
 }this.time+=ms;}
 latency(e){return ({eth:2,can:4,lin:20,a2b:2,rf:e.from==='phone'&&e.to==='screen'?30:80,pilot:80,signal:1,hv:1})[e.bus]||1;}
 next(){if(['done','failed'].includes(this.status))return null;this.status='running';const e=this.queue[this.cursor++];if(!e){this.status='done';return null;}this.active=e.edge?e:null;
  if(e.edge){if(e.from==='gw'&&e.route[0]==='screen'&&!this.state.authorized){this.fail('Gateway: IVI komutu yetkisiz',e,'REJECT');return e;}this.emit('TX',e,e.signal,`${byId[e.from].tag} → ${byId[e.to].tag}`);if(!this.available(e)){this.integrate(e.bus==='lin'?200:e.bus==='rf'?2000:100);this.fail('Yanıt yok: hat kesik, düğüm kapalı veya besleme/şebeke kayıp',e);return e;}this.integrate(this.latency(e));if(e.effect)this.effect(e.effect,e.value);if(e.to==='cluster')this.reportCluster();this.emit(e.kind==='power'?'POWER':'RX',e,e.signal,e.value==='actual'?this.actual(e.signal):String(e.value??'Aktarım'));
  }else if(e.kind==='check'){const [ok,why]=this.guard(e.rule);this.integrate(1);if(!ok){if(e.rule==='precharge')this.integrate(Math.max(0,parameters.prechargeTimeout-700));this.fail(why,e,'REJECT');return e;}this.emit('PASS',e,e.label,'Koşul sağlandı');
  }else if(e.kind==='wait'){this.integrate(e.ms);this.emit('STATE',e,e.label,this.actual('state'));
  }else{this.effect(e.op);this.integrate(1);this.emit('STATE',e,e.label,this.actual('state'));}
  this.enforce();if(this.cursor>=this.queue.length&&this.status!=='failed')this.status='done';return e;
 }
 actual(signal){const s=this.state;if(/Window|WINDOW/.test(signal))return `Gerçek: %${Math.round(s.window*100)} · HMI: %${Math.round(s.windowReported*100)}`;if(/Temp|HVAC/.test(signal))return `${s.cabin.toFixed(2)} °C`;if(/SOC/.test(signal))return `%${s.soc.toFixed(3)}`;if(/Speed/.test(signal))return `${s.speed.toFixed(1)} km/sa`;return `${s.mode} · ${s.busV.toFixed(1)} V · ${s.power.toFixed(2)} kW`;}
 circuit(route,type){return route.slice(1).every((to,i)=>{const w=link(route[i],to,type);return w&&!this.cuts.has(w.id)&&!this.offline.has(to)&&!this.offline.has(route[i]);});}
 enforce(){const s=this.state;if(s.plug||!s.hv||!this.powered('vcu')||!this.powered('inverter')||!this.circuit(['battery','pdu','inverter','motor'],'hv')){s.ready=false;s.torque=0;if(!s.charging)s.power=0;}if(s.torque&&!this.circuit(pt('vcu','inverter'),'can')){this.integrate(100);s.torque=0;s.power=0;s.fault='İnverter tork mesajı zaman aşımı';this.emit('WATCHDOG',null,'TorqueTimeout','100 ms · tasarım varsayımı');}if(s.charging&&(!this.powered('bms')||!this.powered('evcc')||!this.circuit(s.chargeContactor?['evse','port','charge','battery']:['evse','port','obc','battery'],'hv'))){s.charging=false;s.power=0;s.chargeContactor=false;this.emit('LOCAL',null,'ChargeStop','Şarj yolu kaybında enerji aktarımı kesildi');}if(!this.powered('screen')){s.music=false;s.camera=false;}if(!this.powered('camera')||!this.circuit(['camera','screen'],'eth'))s.camera=false;if(!this.powered('hvac')||!s.hv)s.ac=false;if(!this.powered('pump'))s.cooling=false;if(!this.powered('lights'))s.lights=false;if(!this.powered('wiper'))s.wiper=false;}
 cut(id,on=true){on?this.cuts.add(id):this.cuts.delete(id);this.emit('FAULT',null,on?'Hat açıldı':'Hat onarıldı',id);this.enforce();}
 setOffline(id,on=true){on?this.offline.add(id):this.offline.delete(id);this.emit('FAULT',null,on?'Düğüm kapalı':'Düğüm açık',byId[id].tag);this.enforce();}
 command(name,value){const programs={window:windowCommand(value),climate:value===false?[message(['screen','gw'],'eth','HVAC_ENABLE',false),check('authorized','Konfor kontrol yetkisi','r155'),message(pt('gw','hvac'),'can','HVAC_ENABLE',false,{effect:'acOff'})]:hvacRequest.map(e=>['CabinTarget','HVAC_TEMPERATURE_SET'].includes(e.signal)?{...e,value}:e),media:scenarios.find(s=>s.id==='music').steps,lights:[req('zfr','LightingRequest',value),check('authorized','Gövde kontrol izni','r155'),message(['zfr','lights'],'lin','LowBeam',value,{effect:value?'lights':'lightsOff'})],wiper:[req('zfr','WiperRequest',value),check('authorized','Gövde kontrol izni','r155'),message(['zfr','wiper'],'lin','WiperSpeed',value,{effect:value?'wiper':'wiperOff'})],lock:[req('bcm','LockRequest',value),check('authorized','Kilit kontrol izni','r155'),message(['bcm','lock'],'signal','LockTarget',value,{effect:value?'lock':'unlock'}),ack('bcm','LockStatus',value)]};if(!programs[name])throw new Error('Bilinmeyen komut');if(this.status==='running')this.emit('CANCEL',null,'Önceki komut','Yeni kullanıcı komutu ile sıra değiştirildi');this.queue=this.expand(programs[name]);this.cursor=0;this.status='idle';this.failure=null;this.active=null;this.state.command=name;this.emit('INPUT',null,'IVI komutu',`${name}: ${value}`);}
 report(){return {schema:'ev-atolye/2',scope:'M1 AB davranış simülasyonu; homologasyon kanıtı değildir',scenario:this.scenario.id,initialState:this.initialSnapshot,parameters,virtualTimeMs:this.time,status:this.status,failure:this.failure,state:{...this.state},cuts:[...this.cuts],offline:[...this.offline],trace:this.trace.map(e=>({...e}))};}
}
