export function cockpitMarkup(icon){
 const apps=[['home','layout-grid','Ana ekran'],['vehicle','car-front','Araç'],['media','music-2','Medya'],['navigation','navigation','Navigasyon'],['energy','zap','Enerji']];
 return `<section class="cockpit togg-cockpit">
 <div class="cockpit-heading"><span>T10F · UÇTAN UCA EKRAN</span><div><button id="cockpit-reference" title="T10F kokpit fotoğrafı">${icon('images')}</button><button id="cockpit-expand" title="Kokpiti büyüt">${icon('maximize-2')}</button></div></div>
 <div class="panoramic-dash">
 <div class="instrument-wrap"><div class="display-label"><button data-focus="cluster">12,3″ · Gösterge ${icon('arrow-up-right')}</button><span id="cluster-link"></span></div>
 <div id="cluster-display" class="instrument display"><div class="telltales"><span id="tell-ready">READY</span><span id="tell-lights" title="Farlar">${icon('lightbulb')}</span><span id="tell-brake" title="Park freni">${icon('circle-parking')}</span><span id="tell-fault" title="Sistem uyarısı">${icon('triangle-alert')}</span><span id="tell-charge" title="Şarj">${icon('plug')}</span></div>
 <div class="instrument-core"><div class="power-gauge"><span>ANLIK GÜÇ</span><strong id="icm-power">0.0</strong><small>kW</small><div><i id="power-fill"></i></div><em>CHARGE / POWER</em><span id="icm-temp">28 °C</span></div><div class="togg-dial"><div class="dial-arc"></div><div class="speed-readout"><strong id="icm-speed">0</strong><span>km/sa</span></div><div class="lane-graphic"><i></i>${icon('car-front')}<i></i></div><div class="gear"><b data-gear="P">P</b><b data-gear="R">R</b><b data-gear="N">N</b><b data-gear="D">D</b></div></div><div class="charge-readout"><span>BATARYA</span>${icon('battery-medium')}<strong id="icm-soc">72.0%</strong><div><i id="battery-fill"></i></div><span>Comfort</span></div></div><div id="icm-warning">PARK</div><div class="icm-bottom"><span id="icm-voltage">DC-link 0 V</span><span id="icm-ecall">eCall hazır</span></div><div class="power-off">Gösterge beslemesi yok</div></div></div>
 <div class="ivi-wrap"><div class="display-label"><button data-focus="screen">29″ · Bilgi-eğlence ${icon('arrow-up-right')}</button><span id="ivi-link"></span></div>
 <div class="infotainment display" id="ivi-display"><div class="ivi-top"><b>Togg</b><span id="ivi-network">LTE çevrimdışı</span><span id="ivi-phone">Telefon yok</span><time id="ivi-time">09:41</time></div>
 <div class="panorama-content"><div class="profile-rail"><span>Misafir</span><small>Comfort</small><span class="compass">K</span><span class="compass-direction">GB</span><small id="upper-weather">28 °C</small></div><div class="panorama-map"><canvas id="panorama-map" width="700" height="300"></canvas><span class="map-search">${icon('search')}Nereye gitmek istersiniz?</span><span class="map-pin">${icon('navigation')}</span><span class="map-caption">Gemlik · örnek rota</span></div><div class="passenger-panel"><div class="trip-stats"><div><span>Batarya</span><b id="upper-soc">72%</b></div><div><span>Anlık güç</span><b id="upper-power">0 kW</b></div></div><img src="${import.meta.env.BASE_URL}assets/t10f-official.webp" alt="Togg T10F üretici görseli"><span class="passenger-caption" id="upper-status">T10F · Comfort</span><div id="upper-media" hidden><span>Medya</span><b>Elektrik</b><small>Örnek parça</small>${icon('audio-lines')}</div></div></div><div class="power-off">Multimedya beslemesi yok</div></div></div></div>
 <div class="dash-trim"><span></span><div class="air-vent"><i></i><i></i><i></i></div><span></span></div>
 <div class="lower-console"><div class="console-side"><span>POWER</span><button id="console-power" title="Aracı çalıştır / kapat">${icon('power')}</button></div><div class="control-wrap"><div class="display-label">8″ · Dokunmatik kumanda</div><div id="control-display" class="display control-display"><div class="control-header"><button data-screen="home" title="Ana ekran">${icon('layout-grid')}</button><span id="control-title">Ana ekran</span><span class="control-lock">${icon('lock-keyhole')}</span></div><div id="ivi-content"></div><nav class="ivi-nav">${apps.map(([id,i,l])=>`<button data-screen="${id}" title="${l}">${icon(i)}<span>${l}</span></button>`).join('')}</nav><div class="climate-bar"><button id="temp-minus" title="Sıcaklığı azalt">${icon('minus')}</button><strong id="temp-target">22°</strong><button id="temp-plus" title="Sıcaklığı artır">${icon('plus')}</button><button id="climate-on" title="Klima">${icon('snowflake')}<span>A/C</span></button><span id="cabin-value">Kabin 28°</span><button id="defrost" title="Buğu çözme doğrulama kapsamı">${icon('wind')}</button></div></div></div><div class="console-side"><button id="console-warning" title="Güvenlik gereksinimleri">${icon('triangle-alert')}</button></div></div>
 </section>`;
}

export function paintMap(canvas){
 const c=canvas.getContext('2d'),w=canvas.width,h=canvas.height;c.fillStyle='#111d2b';c.fillRect(0,0,w,h);
 const roads=[[[0,230],[160,145],[290,168],[470,90],[700,115]],[[90,0],[130,85],[285,170],[390,300]],[[510,0],[485,80],[560,300]],[[0,50],[230,68],[440,20]],[[10,300],[285,168],[375,0]],[[200,300],[450,208],[700,205]]];
 c.lineCap='round';c.lineJoin='round';for(const p of roads){c.beginPath();p.forEach(([x,y],i)=>i?c.lineTo(x,y):c.moveTo(x,y));c.strokeStyle='#070f19';c.lineWidth=13;c.stroke();c.strokeStyle='#36485d';c.lineWidth=6;c.stroke();}
 c.strokeStyle='#81b6d8';c.lineWidth=6;c.beginPath();c.moveTo(348,255);c.lineTo(285,168);c.lineTo(470,90);c.lineTo(488,30);c.stroke();
 c.fillStyle='#9eacbd';c.font='12px Arial';c.fillText('GEMLİK',55,175);c.fillText('Bursa Yolu',408,270);c.fillText('Sahil',550,172);c.fillStyle='#287494';c.beginPath();c.arc(488,30,8,0,Math.PI*2);c.fill();
}
